### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by Northshoot** [LINCnil/pia#10]
Hey,

I start by running
`nmp install`

followed by 

'ng build'

which result in a sequence of errors:

```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
Module build failed:
@import "../../../node_modules/ngx-chips/dist/modules/core/styles/core/_core.scss";
^
      File to import not found or unreadable: ../../../node_modules/ngx-chips/dist/modules/core/styles/core/_core.scss.
Parent style sheet:<path>/LINCnil/pia/src/assets/stylesheets/_tags.scss
      in <path>/LINCnil/pia/src/assets/stylesheets/_tags.scss (line 1, column 1)
Error:
@import "../../../node_modules/ngx-chips/dist/modules/core/styles/core/_core.scss";
^
      File to import not found or unreadable: ../../../node_modules/ngx-chips/dist/modules/core/styles/core/_core.scss.
Parent style sheet: <path>/LINCnil/pia/src/assets/stylesheets/_tags.scss
      in <path>/LINCnil/pia/src/assets/stylesheets/_tags.scss (line 1, column 1)
    at options.error (<path>/LINCnil/pia/node_modules/node-sass/lib/index.js:291:26)
 @ ./src/styles.scss 4:14-191
 @ multi ./src/styles.scss

```

**Comment by iouss** [comment]
Hello,
I found workaround for this issue and it works for me, I have compiled the application in another machine Win10 and I have got no error. so I copied the missing files from this machine to my VM Win Server 2012r2 on node_modules\ngx-chips
I started the server with ng serve and it worked, so I build a dev version with ng build, I have got the dist folder, I copied it to a web server and it works now ( Frontend with Backend)
But the ng build -prod doesn’t work for me
Now I'm using the dev version for test and hope for the final version
you can found my ngx-chips in attachment if you want to use it

[ngx-chips.zip](https://github.com/LINCnil/pia/files/1576354/ngx-chips.zip)

Thanks
Oussama

**Comment by brunto** [comment]
Hello,
This error is reported here: https://github.com/Gbuomprisco/ngx-chips/issues/632 we have fixed the application, it will be ok in the version 1.5 (Coming soon)
See: https://github.com/LINCnil/pia/commit/005316609567b4a1a91c4bc1e2bbc3cb1fa13fcc
