### ISSUE TITLE
Dispo en machine virtuel

### ISSUE THREAD

**Issue by ghost** [LINCnil/pia#109]
Bonjour, 
n'avez vous pas la possibilité de proposer l'outil sous forme de OVA donc machine virtuelle, 

car l'installation de votre outil en front et back, n'est vraiment pas facile à réaliser.

merci de votre retour.

**Comment by ylachgar** [comment]
Bonjour @Spartacus2018 ,

En effet, il n'y a pas encore de VM, mais vous pouvez utiliser le Runbook pour une installation Step by Step.
N’hésitez pas à me contacter.

**Comment by eglyn** [comment]
Je plussoie pour une VM, car le Runbook est plutôt incompréhensible pour ma part, j'ai abandonné l'installation ^^,

**Comment by ylachgar** [comment]
Bonsoir @eglyn,

Si vous le souhaitez je peux vous aider a faire l'installe en remote et a update le runbook car la VM ne devrais pas arriver tout de suite, néanmoins le docker est déjà presque validé il me semble.

**Comment by eglyn** [comment]
@ylachgar 
Merci de votre proposition, mais si le docker est bientôt disponible, je vais l'attendre, ce sera plus simple :)

**Comment by tocks53** [comment]
Bonjour @ylachgar , j'ai essayé de suivre le runbook. Mais sans y arrivé.

J'en suis à l'étape 3.5.5, mais je comprends pas ce que je doit faire.

Pourrais tu détaillé le runbook. stp

Pourrais tu également expliqué la partie 3.6 : Nous devons indiqués les user et mdp créé précédemment. mais on nous a demandé juste de créer l'useradmin. Cela n'est pas très compréhensible.

En tous cas merci pour ton implication sur le projet

**Comment by nanii-60** [comment]
@ylachgar serait-ce possible de faire un remote ?

**Comment by brunto** [comment]
Vous pouvez aussi utiliser la version docker disponible ici : https://github.com/kosmas58/pia-docker

**Comment by liberodark** [comment]
j'ai aussi monté deux install pour pia front pour debian et centos.
Seule soucis je cherche pour le SSL.
