### ISSUE TITLE
PIA non reconnue comme angular-cli project

### ISSUE THREAD

**Issue by CCoruble** [LINCnil/pia#11]
Bonjour,

Lorsque j'essaye d'executer "ng serv" dans le dossier "PIA", celui-ci me retourne l'erreur suivante:
"You have to be inside an angular-cli project in order to use the serve command."

Je ne suis pas familier du monde de angular-cli et j'ai eu beaucoup de soucis à l'installation.
Lorsque je crée un nouveau projet comme décrit dans le README de angular/cli cela fonctionne très bien, j'en déduis que "PIA" n'est pas reconnue comme un projet angular/cli.

Que faire pour résoudre ce problème ? 
Merci d'avance,
Cordialement

**Comment by CCoruble** [comment]
Le dossier PIA se trouve dans "C:\Users\User_Name\pia", faut-il qu'il soit placé dans un emplacement en particulier ? 
Lorsque j'exécute la commande "npm start" il sort l'erreur suivante:
"webpack: failed to compile"

**Comment by brunto** [comment]
Bonjour,
Je vous encourage à vérifier deux choses : 
1. L'installation de angular-cli : https://cli.angular.io
2. L'installation des modules nodes via la commande : `npm install` ou `yarn`

**Comment by CCoruble** [comment]
Bonjour,

Merci de votre réponse, j'ai utilisé la commande npm install -g @angular/cli pour l'installation. Presque tout le temps l'installation n'était pas complète à cause de certains modules mais j'ai réussi à avoir tous les packets nécessaires.
Cependant cela ne fonctionnait pas et j'obtenais le résultat énoncé plus haut.

**Comment by CCoruble** [comment]
En trafficotant à droite à gauche sur ubuntu j'arrive à la même erreur webPack: Failed to compile.
Ci joint le (lien du) screenshot qui montre la totalité du message d'erreur.
https://www.noelshack.com/2017-50-4-1513244151-pia-error.png

**Comment by CCoruble** [comment]
Ne comprenant pas l'entièreté de angular et NPM je ne suis pas sûr des résultats trouvés néanmoins les voici:

Après vérification le fichier censé se trouver ici "../../../node_modules/ngx-chips/dist/modules/core/styles/core/_core.scss" n'existe pas !
Lorsque j'ai utilisé npm install ngx-chip pour l'installer celui contenait bien un dossier "dist" mais avec seulement "ngx-chips.bundle.js" à l'intérieur.

En regardant la structure du github de ngx-chips (https://github.com/Gbuomprisco/ngx-chips) je ne trouve aucun chemin correspondant à celui qui est donné dans l'erreur.

Le fichier importé est donc inexistant ? Ou le chemin est-il basé sur une ancienne architecture qui n'est plus à jour ?

Je suis complètement bloqué pour lancer pia ...
Merci d'avance.

**Comment by brunto** [comment]
Le problème sera corrigé dans la prochaine version.
Vous pouvez trouver la solution ici: #10
