### ISSUE TITLE
Version 1.6 issue

### ISSUE THREAD

**Issue by ylachgar** [LINCnil/pia#122]
Salut Les gars,

Après la mise a jour 1.6 j'ai quelques problème pour la faire fonctionner correctement : 

![image](https://user-images.githubusercontent.com/35890640/36682209-cd264638-1b1a-11e8-9941-789677bdc648.png)

J'ai essayer diverse actions comme reinstaller Angular cli, downgrade a une version 1.6.8, plusieurs reinstall mais je n'arrive pas a resoudre le pb.

j'ai aussi noté que la version du json indique toujours 1.5.0 

![image](https://user-images.githubusercontent.com/35890640/36682297-04dcd13c-1b1b-11e8-8ba6-1021a468dbd7.png)

**Comment by brunto** [comment]
Bonjour,

1. Avez-vous fais un `npm install` avant le `ng build .....` ?
2. Effectivement nous avons omis de mettre le bon numéro de version dans le package.json merci pour l'info, nous allons rectifier.

**Comment by ylachgar** [comment]
Bonjour Bruno,

Yep, npm install, @angular-cli  etc ... mais j'ai tjrs la meme erreur  meme avec la version 1.4.9  de cli

**Comment by brunto** [comment]
Vous pouvez essayer les commandes suivantes ?
```
npm cache verify
npm -g i @angular/cli
```

**Comment by ylachgar** [comment]
Bonjour @brunto 

Voici les resultats : 

![image](https://user-images.githubusercontent.com/35890640/36718078-cfa6ee54-1ba0-11e8-8193-fa647b147fe8.png)

![image](https://user-images.githubusercontent.com/35890640/36718271-742b0e6a-1ba1-11e8-9e67-3d5b737ac2c8.png)

**Comment by ylachgar** [comment]
Une autre info a prendre en compte, j'essaie de run la version 1.6 de PIA avec la version 1.1 de Pia Back.
Il y a peut etre un lien entre les deux ... :)

**Comment by ylachgar** [comment]
Apres install sur un server frais pas de soucis.

**Comment by ylachgar** [comment]
J'ouvre un nouveau bug sur la version back de PIA la version front est validé de mon coté :)
