### ISSUE TITLE
impossible de compiler pour l'environnement de prod

### ISSUE THREAD

**Issue by cchauveau** [LINCnil/pia#126]
Bonjour,
lorsque je veux compiler l'environnement de prod avec la commande 
`ng build --prod --build-optimizer --sourcemaps`
j'ai l'erreur suivante

> Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined

Mais je peux lancer l'application en dev via
`ng serve`
Pouvez-vous m'aider?

**Comment by ylachgar** [comment]
Bonjour @cchauveau,

Avez vous un fichier nommer environment.prod.ts dans votre dossier Pia>>src>>environments ?
Avez vous également jeter un oeil aux différentes étapes indiquées dans le Run Book ?

je le remet ici : https://github.com/LINCnil/pia/files/1723460/PIA.Technical.Runbook.docx

**Comment by cchauveau** [comment]
Merci @ylachgar ,
j'avais juste suivi les infos du Readme, je n'avais pas vu le fichier RunBook.
c'est résolu.

**Comment by ylachgar** [comment]
Rien ne me fait plus plaisir que d'aider à résoudre un problème ! 
N'hésitez pas a me joindre si vous avez des questions
