### ISSUE TITLE
unknown attribute 'people_names' for Pia.

### ISSUE THREAD

**Issue by junghansw** [LINCnil/pia#129]
Hello,

we have a fresh installation of pia-back and pia frontend on CentOS 7. We can not create a new PIA. When clicking on the start button the PIA is not created (create windows stays open) and the following error is logged in pia-back.

from pia-back production.log:
I, [2018-02-28T17:08:37.372801 #5045]  INFO -- : [a05c53f3-3c18-4385-9293-6e676b4b170a]   Parameters: {"pia"=>{"name"=>"bla", "author_name"=>"test", "evaluator_name"=>"test", "validator_name"=>"test", "dpo_status"=>"undefined", "dpo_opinion"=>"undefined", "concerned_people_opinion"=>"undefined", "concerned_people_status"=>"undefined", "rejected_reason"=>"undefined", "applied_adjustements"=>"undefined", "created_at"=>"Wed Feb 28 2018 17:08:37 GMT+0100 (Mitteleuropäische Zeit)", "updated_at"=>"undefined", "status"=>"0", "is_example"=>"0", "dpos_names"=>"undefined", "people_names"=>"undefined", "concerned_people_searched_opinion"=>"undefined", "concerned_people_searched_content"=>"undefined"}}
I, [2018-02-28T17:08:37.377399 #5045]  INFO -- : [a05c53f3-3c18-4385-9293-6e676b4b170a] Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms)
F, [2018-02-28T17:08:37.379348 #5045] FATAL -- : [a05c53f3-3c18-4385-9293-6e676b4b170a]
F, [2018-02-28T17:08:37.379523 #5045] FATAL -- : [a05c53f3-3c18-4385-9293-6e676b4b170a] **ActiveModel::UnknownAttributeError (unknown attribute 'people_names' for Pia.)**:
F, [2018-02-28T17:08:37.379608 #5045] FATAL -- : [a05c53f3-3c18-4385-9293-6e676b4b170a]
F, [2018-02-28T17:08:37.379703 #5045] FATAL -- : [a05c53f3-3c18-4385-9293-6e676b4b170a] app/controllers/pias_controller.rb:23:in `create'

`

**Comment by brunto** [comment]
Hello,
Do you run `bin/rake db:migrate`?

**Comment by junghansw** [comment]
Hello brunto,
you're right. The tables hasn`t been created. postgres was 9.2, switched to 9.6 and created the tables. 

Thank you very much.
