### ISSUE TITLE
Add a simple command to package.json for production

### ISSUE THREAD

**Issue by KillianKemps** [LINCnil/pia#130]
Hello,

It would be nice to have a command in `package.json` to build the app for production purpose.
When I maintain the Dockerfile, I would like to do just `yarn run build:prod` for example without having to know that  `ng build --prod --build-optimizer --sourcemaps` is being made.

You as the app developer could simply change the command in the `package.json` when doing a new release without having to change everything behind.

I'm suggesting this as I saw that the instructions changed with the `1.6.0` release. Before it was `ng build -prod`, now it is `ng build --prod --build-optimizer --sourcemaps`

**Comment by brunto** [comment]
Hello,
Good idea we'll see to add it for the next version.
We changed the build instruction according to the documentation: https://angular.io/guide/deployment#build-with---prod

**Comment by brunto** [comment]
Done in f0e9b0e54fe48b534422bbea339b3900d7957257 with the command `yarn prod` it will be in the next version of the application.
