### ISSUE TITLE
Secure the access to the application

### ISSUE THREAD

**Issue by jsefe92** [LINCnil/pia#134]
Hello,
Is there any way to integrate the front-end of PIA with CAS?

**Comment by brunto** [comment]
Hello,
For now the application has no authentication system.
Everyone can develop secure access (CAS, ...) and integrate it into the application.

**Comment by onefitmedical** [comment]
Bonjour,

A ce jour est-ce que le développement d'un système d'authentification est prévu?

Merci d'avance

**Comment by brunto** [comment]
Bonjour,
Non pas pour le moment.

**Comment by kevin-atnos** [comment]
Hello,

The next version (3.1) will have an authentication module with users, roles, profiles and rights management.
This new version should come this autumn 2021.

Thank you,

Bonjour,

Pour information, la prochaine version (3.1) contiendra un module de gestion des utilisateurs et de rôles/profils/droits.
Elle devrait arriver pendant l'automne.

Cordialement,
