### ISSUE TITLE
Add documentation to run on OSx

### ISSUE THREAD

**Issue by bbouille** [LINCnil/pia#142]
It would be great to get a beginner guide to set up the web apps on localhost (OSx) for testing purpose.

**Comment by bbouille** [comment]
Here are some notes to resolve this issue : 
1. Set up the Back End app on OSx : http://bbouille.github.io/2018/03/03/Get-PIA-app-from-srcatch-p1/
2. Set up the Front End app on OSx : http://bbouille.github.io/2018/03/05/Get-PIA-app-from-srcatch-p2/

Source code available : https://github.com/bbouille/bbouille.github.io/tree/master/_posts

**Comment by brunto** [comment]
You can also use the docker version: https://github.com/kosmas58/pia-docker
