### ISSUE TITLE
Cannot ask for review when connected to backend

### ISSUE THREAD

**Issue by romoloman** [LINCnil/pia#158]
When connected to the backend the ask for review only works in Planned or Existing measures while working in offline mode it works in every section of the PIA
Howto reproduce:
open the pia app in standalone mode, import the pia provided in the example
Ask for review works in every section of the pia.
now set the backend url:
import again the pia provided in the example:
ask for review only works in the "Planned or existing measures" section

[pia-example.zip](https://github.com/LINCnil/pia/files/1828412/pia-example.zip)

Tested on a clean checkout of "develop" branch of pia vs
clean checkout of master branch of pia-back

pia-1.6.0 vs the same backend works.

**Comment by Humgrim** [comment]
Bonjour,

Je fais face au même problème sur la version 1.6.0
Si le front est relié au back lors de l'évaluation d'un PIA si l'évaluateur clic sur le bouton "A corriger" et valide en suite l'évaluation, le PIA retourne en mode "édition". Une fois le PIA corrigé, on est bloqué en mode "édition ", car le bouton "Demander l'évaluation" ne fonctionne plus.

Il semble que le problème vienne de la colonne "global_status" de la table "evaluations"qui reste avec la valeur "1" après le clic sur "A corriger" ce qui empêche le passage en mode "évaluation".
Si l'on fait un update sur la table "evaluations" et que l'on donne la valeur "0" à la colonne "global_status" de notre évaluation on peu de nouveau évaluer le PIA.

Merci de votre aide

**Comment by Charles68** [comment]
I'm facing the same issue.

**Comment by brunto** [comment]
Hello,
Did you try with version 2 released in December 2018?
For me everything works fine with this version.

**Comment by kevin-atnos** [comment]
@romoloman @Charles68 @Humgrim  :
Did you try latest PIA version? Does the problem still appear?

Thank you.
