### ISSUE TITLE
[Formulaire] Plusieurs éléments du formulaire avec le même nom

### ISSUE THREAD

**Issue by TheMalloum** [LINCnil/pia#160]
Bonjour,

J'essaie de connecter le front PIA à un back-Office dévellopé en JAVA.
Je m'appuie sur le fichier swagger.yml Comme évoqué dans le bug #2

J'ai des remarques à vous remonter sur le fichier swagger.yml mais une en particulier me pose problème;
Lors de la création/update d'un "Answer", la partie front  envoie un formulaire de la manière suivante. 

<img width="507" alt="capture d ecran 2018-03-23 a 09 42 57" src="https://user-images.githubusercontent.com/1165036/37839848-d127b5e6-2ebb-11e8-893d-183f73901fd0.png">

Comme vous le voyez, on utilise le même nom "answer[data][list][]", plusieurs fois dans le même formulaire
Il apparait que les spécifications ne l'Interdisent pas ( [comme dit ici](https://stackoverflow.com/questions/452066/html-form-with-multiple-hidden-control-elements-of-the-same-name) ).

mais comme il est aussi dit : 

> Programs are supposed to group identically named items together. While the HTML specification doesn't explicitly say this, it is implicitly stated in the documentation on checkboxes.

Serait-il possible de changer le fonctionnement  actuel de :

answer[data][list][] = aa
answer[data][list][] = bb
answer[data][list][] = cc

à 
answer[data][list] = aa bb cc 

Malloum LAYA
[https://carto-si.com](url)
![logo-mini](https://user-images.githubusercontent.com/1165036/37840647-f47918e4-2ebd-11e8-9759-776c08e11922.png)

**Comment by TheMalloum** [comment]
Bonjour @brunto,

Je vois que tu es assigné sur ce bug.
Pour te faire gagner du temps, il semble que le code à modifier est dans le fichier answer.model.ts ligne environ ligne 98 méthode   private setFormData(data) 

remplacer : 

> if (data[d].hasOwnProperty(d2)) {
>               if (data[d][d2] instanceof Array) {
>                 for (const d3 in data[d][d2]) {
>                   if (data[d].hasOwnProperty(d2)) {
>                     if (data[d][d2][d3]) {
>                       formData.append('answer[' + d + '][' + d2 + '][]', data[d][d2][d3]);
>                     }
>                   }
>                 }
>               } 

par 

> if (data[d][d2] instanceof Array) {
>                       formData.append('answer[' + d + '][' + d2 + ']', data[d][d2].join(" ")
>               }


Souhaites-tu que je propose un pull-request ?

**Comment by brunto** [comment]
Bonjour,
Ce n'est pour le moment pas d'actualité de modifier ce comportement, tu peux soumettre une PR effectivement afin qu'on puisse l'étudier.
