### ISSUE TITLE
[Cookies] Envoie des cookies en mode CORS

### ISSUE THREAD

**Issue by TheMalloum** [LINCnil/pia#161]
Bonjour,

J'utilise les cookies pour ajouter une authentification au PIA.
Cependant la partie front du pia n'est pas paramètré pour envoyer les cookies.

Pouvez-vous ajouter cette option comme indiqué [ici](https://stackoverflow.com/questions/47304912/angular-4-setting-withcredentials-on-every-request-cors-cookie) ?

**Comment by TheMalloum** [comment]
J'ai poussé l'analyse, le problème est résolu si vous ajouter les propriété "mode" et "credentials" dans les appels **fetch** 

Il faut donc remplacer : 

> fetch(this.getServerUrl(), {
>           method: 'POST',
>           body: formData,
>         })

par  : 

> fetch(this.getServerUrl(), {
>           method: 'POST',
>           body: formData,
>           mode : 'cors',
>           credentials : 'include'
>         })

**Comment by LaboCNIL** [comment]
Merci pour cette contribution @TheMalloum qui peut en effet se révéler utile pour d'autres !

**Comment by TheMalloum** [comment]
Bonjour,

Cela signifie que cette correction va être apportée sur votre code ?

Suuhaitez-vous que je propose un pull request ?

Malloum
