### ISSUE TITLE
Possibilité d'exporter en PDf

### ISSUE THREAD

**Issue by jgarcin** [LINCnil/pia#17]
Bonjour, 

Serait-il possible de prévoir la fonctionnalité d'export en PDF dans les différentes versions de la solution ? 
Car si l'on peut exporter facilement les données, on ne peut pas récupérer les graphiques réalisés ce qui est fort dommage. 

Merci par avance!

**Comment by LaboCNIL** [comment]
Bonjour

Une fonctionnalité d'export des visuels de l’analyse (vue d’ensemble des risques, cartographies des risques et vue d’ensemble du plan d’action) est maintenant intégrée au niveau de l'affichage du rapport PIA. 

//

A new feature has been implemented allowing to export the PIA’s visual elements (risk overview, risk mapping, action plan overview) from PIA report page.
