### ISSUE TITLE
develop - risks cartography is not correctly shown, when frontend is connected to the backend

### ISSUE THREAD

**Issue by kosmas58** [LINCnil/pia#192]
![connected](https://user-images.githubusercontent.com/43474/38383898-fe715474-390d-11e8-9b2e-4a4ed72e6ae9.png)

Only the background is shown, no bubbles, no arrows and no  riskXLetters are shown. This problem occurs everytime you're connected to the backend, no matter

1. when starting the frontend locally with `yarn` or `npm` `start`

1. or generating `pia-app` out of the source with option `build --prod --build-optimizer --sourcemaps`

1. or generating the frontend in prod mode in a docker container and so on ...

When not connected to the backend risk mapping is shown in all cases.

![not connected](https://user-images.githubusercontent.com/43474/38383914-06ba18b4-390e-11e8-8a8e-2bb4cc152c35.png)

I've used your actual `develop` version from [GitHub](https://github.com/LINCnil/pia).

In your version the arrows are only weakly displayed. I've changed this in `risks-cartography.component.ts` to:
`   // Dotted lines params`
    `  context.setLineDash([2, 2]);`
      `context.lineWidth = 2;`
in my develop version. That leads to better visibility.

![improved](https://user-images.githubusercontent.com/43474/38384683-199e43ae-3910-11e8-8614-2b18e8b962c7.png)

**Comment by brunto** [comment]
Hello,
I'll review this soon.

**Comment by kevin-atnos** [comment]
Hello,

We will try to fix it in the next release (beginning of september 2018). If not, it will be fixed in the next release.

Thank you.

**Comment by brunto** [comment]
This is fixed on the master branch of pia-back and pia.
This will be released in the next version 1.6.4
