### ISSUE TITLE
develop - created major update for language support in PIA

### ISSUE THREAD

**Issue by kosmas58** [LINCnil/pia#194]
@LaboCNIL: I've created pull request #193 to improve language and I18n support in PIA. I would be nice, if you are able to pull it. 

 I've improved help. I added the ability to show the Infografics DPIA inside the tool:

![carte de processus](https://user-images.githubusercontent.com/43474/38472261-b8f3b316-3b7d-11e8-8214-cd2b47b48e6b.jpg)

 Corina Scheiter from the Bavarian DPA created a section "First Steps":

![premieres etapes](https://user-images.githubusercontent.com/43474/38468814-5e35d6c0-3b4b-11e8-9ea0-498f7f584ce2.jpg)

As you can see on GitHub, I'm constantly working on the improvement of your marvellous tool.

I am a full time DPO at a large clinic in Munich and work in my spare time on the further development of the PIA application stack, because I'm with Ruby on Rails since 2007. In the meantime, Corina Scheiter from the Bavarian DPA supports my work. That's a real public private partnership.

Thanks in advance.

Kosmas

**Comment by brunto** [comment]
See the PR: https://github.com/LINCnil/pia/pull/304
