### ISSUE TITLE
Connect pia front to custom api rest

### ISSUE THREAD

**Issue by TheMalloum** [LINCnil/pia#2]
Hi,

I want to connect pia to my api rest.
It's will be nice to have specifications of api rest for the back (and why not in json)

Thanks

**Comment by brunto** [comment]
Hi,
You can connect the PIA application to your API REST without problem.
You can read the documentation here: https://piaback.docs.apiary.io and of course we used the JSON format.
Also the swagger file is here: https://github.com/LINCnil/pia-back/blob/master/swagger.yaml

Regards

**Comment by TheMalloum** [comment]
cool thanks @brunto

**Comment by TheMalloum** [comment]
Hi,

The IHM send Rest request (create PIA) but the Content-type is somethinks like this : 

multipart/form-data; boundary=----WebKitFormBoundaryr7P4prhmBqwqjQb3

instead of "application/json" define in the swagger : https://github.com/LINCnil/pia-back/blob/master/swagger.yaml

Is-it correct ?

**Comment by brunto** [comment]
HI,
You're right there was an error in the swagger file. This is corrected in the last commit in the develop branch here: https://github.com/LINCnil/pia-back/commit/1b5d2560d68389b81cd5a52b50e35f4ba9eb19d8#diff-bac86ae86657c2fa2c3dd2ab26df4960L19
Thanks for your feedback.

**Comment by TheMalloum** [comment]
thanks @brunto,

I have some problem to generate stub server API with swagger maven pluggins with resteasy.

I logged an issue here https://issues.jboss.org/browse/RESTEASY-1769 

As soon as i fix my bug , i 'll come back to you.

Malloum
