### ISSUE TITLE
src/styles.css manquant

### ISSUE THREAD

**Issue by test950** [LINCnil/pia#203]
Bonjour,

quand je lance un ng serve ou ng build j'ai un message d'erreur m'indiquant que le fichier src/styles.css est manquant (j'ai bien un fichier styles.scss mais pas de fichier styles.css dans le dossier src)
lorsque je rajoute un fichier styles.css vide a la main je n'ai plus de message et le site fonctionne mais l'afffichage est "buggé", forcement sans feuille de style c'est moche.
pouvez vous me dire ou trouver ce fichier styles.css manquant?

merci pour votre aide.

**Comment by test950** [comment]
[https://image.ibb.co/iiqyMn/pia.jpg](url)
voici une capture d'ecran du site au final qui fonctionne mais s'affiche mal.

**Comment by brunto** [comment]
Bonjour,
`ng serve` compile automatiquement les assets.
Avez-vous un message d'erreur qui s'affiche ?

**Comment by test950** [comment]
le message indique justement que le fichier style.css est manquant.
lorsque je cree a la main un fichier style.css la compilation se termine sans message d'erreur.
et lorsque j'exporte le dossier dist dans le dossier www le site fonctionne bien mais il s'affiche mal vu que la feuille de style n'est pas bonne.
au final c'est inutilisable, si qqu'un pouvait me donner le contenu de ce fichier styles.css ca serait sympa.
merci

**Comment by test950** [comment]
voici le message d'erreur exacte lors de la compilation:
`ERROR in milti ./src/styles.css
Module not found: Error: Can't resolve '/pia/src.styles.css' in '/pia/'`
je pense avoir bien tout installé car j'arrive bien a compilé si un fichier styles.css est bien en place et qu'au final le moteur du site fonctionne, mais sans la feuille de style les boutons sont mal placés, les textes empiètent les uns sur les autres, etc....
inutilisable

**Comment by test950** [comment]
d'ailleurs y'as pas moyen d'avoir une version compilé directement compatible avec apache?
je fais pas d'hebergement web et se prendre la tete a monter une vm, installer tous les prérequis etc.... pour au final compiler une version qui pourrait être proposée directement prete a l'emploi.
je pense que ca simplifierais pas mal la vie.

**Comment by test950** [comment]
up :|

**Comment by labanane34** [comment]
Ahah ça fait plaisir de voir comme le projet est actif hein ? :-)

Si ça peu aider j'ai mis à jours un runbook trouvé sur une des pages de ce projet. J'ai réussi à faire tourner ça sur une 16.04 LTS, même si je pense pas avoir encore tout compris.

Mon sujet est tjs marqué en "help wanted" preuve que personne n'a lu mes messages !
https://github.com/LINCnil/pia/issues/177

Bonne chance l'ami !

**Comment by test950** [comment]
franchement c'est désespérant, aucun support et j'ai toujours pas compris l’intérêt de donner une version a compiler soit même.
c'est un outil qui devrait être facilement déployé dans toutes les entreprises.
pourquoi ne pas rendre disponible une version déjà compilée et prête a l'emploi?

en tout cas merci  pour le message, bon courage a toi aussi.

**Comment by peterhuerlimann** [comment]
@test950 @labanane34 Have you found https://github.com/kosmas58/pia-docker by @kosmas58 and @KillianKemps already? I  personally haven't tried it yet, but could be a starting point in an 'easier to deploy'-version...
