### ISSUE TITLE
No rights to upload/save file in dir

### ISSUE THREAD

**Issue by h00ph3r0** [LINCnil/pia#210]
Good evening from Greece!
I am not allowed to save el.json in the specified directory for the pia translation, due to permission constraints...
Could you please help?

**Comment by FanchTheSystem** [comment]
Hello, you could create a pull request like this:
https://github.com/LINCnil/pia/compare/develop...h00ph3r0:develop

**Comment by LaboCNIL** [comment]
Hi @h00ph3r0,
A greek translation has been provided by @DimitrisTzellis and is available in the 1.6.3 version released today. You can still edit this translation by[ proposing a file change](https://github.com/LINCnil/pia/tree/master/src/assets/i18n#editing-an-existing-translation).
