### ISSUE TITLE
Is this installable on a Windows Server?

### ISSUE THREAD

**Issue by ZakBroome-Levett** [LINCnil/pia#216]
Firstly, let me apologize if this seems like a silly question, I am not familiar with Ubuntu OS / Server.
I have been asked to attempt to deploy this on a Windows Server (virtual machine), and I am struggling to understand what steps are involved in doing so.
I do realise there is a RunBook for Front End and Back End, but it seems to be exclusively for Ubuntu.
So, I am essentially looking for guidance on how to install this and test it on a Windows Server (2012 R2 Standard, if possible).

Can anyone help to enlighten my ignorance please?

Kind Regards

**Comment by kosmas58** [comment]
You can use [my docker configuration](https://github.com/kosmas58/pia-docker) mentioned in [pia-back](https://github.com/LINCnil/pia-back) README.

**Comment by ZakBroome-Levett** [comment]
Many thanks for the clarification, Kosmas.
We'll give it a try. Should I run into any issues in setting up, I hope I can get back to you for any clarifications.

Again, much appreciated.

**Comment by kosmas58** [comment]
It should work under Server 2012. Look at the Docker page for installation information for docker. Maybe you need a Docker Hub account to download the used images.

**Comment by kosmas58** [comment]
Pardon me, you need Windows Server 2016 to run Docker. But you will get Docker Enterprise Edition for Windows Server. It is available for all Windows Server 2016 customers at no additional cost.

**Comment by ZakBroome-Levett** [comment]
Good afternoon.
I have since been able to get a Windows Server 2016 trial for 180 days, which comes with Docker EE, in order to be able to test this.
I am now having trouble running the "docker-compose up" cmd, as I receive the following msg:

PS C:\pia-docker-master\pia-docker-master> docker-compose up
Building cnil-pia-front
Step 1/13 : FROM nginx:1.13
1.13: Pulling from library/nginx
ERROR: Service 'cnil-pia-front' failed to build: no matching manifest for windows/amd64 in the manifest list entries
PS C:\pia-docker-master\pia-docker-master>

I've tried to troubleshoot the issue, but given my lack of experience with using containers / Docker, I'm having a difficult time trying to ascertain how to resolve it.

![info](https://user-images.githubusercontent.com/29098255/40924410-1a67e820-680f-11e8-82ce-5b0d101790aa.PNG)
![version](https://user-images.githubusercontent.com/29098255/40924412-1a8dde54-680f-11e8-9786-74eb23bbab7e.PNG)

Any insight into how to overcome this problem would be greatly appreciated.

Kind Regards

**Comment by kosmas58** [comment]
Good afternoon too.
I'm not a real docker expert either. Docker EE uses windows containers by default. What you need to run pia  are linux containers. So you have to switch to linux containers in your Docker settings. That should solve the problem.

**Comment by ZakBroome-Levett** [comment]
Thanks Kosmas, I think I came to the same conclusion...
I think the core issue is that Linux Containers are only 'supported' on version Windows Server 2016 '1709', and the evaluation version is 1607. Therefore, I'm assuming the docker-compose can only be run on Windows Server 1709.

Would the person who developed the Docker-Compose configuration, for placing it on a Windows Server not encounter this issue? 
Thank again for all your help so far...

**Comment by kosmas58** [comment]
Linux containers are supported since [Windows 1709](https://docs.microsoft.com/fr-fr/virtualization/windowscontainers/deploy-containers/linux-containers). I'm using Docker on WIndows 10 mainly for development purposes. I'm sorry that you have such problems.
