### ISSUE TITLE
PIA Redhat release ?

### ISSUE THREAD

**Issue by xco51** [LINCnil/pia#217]
Hi 
is there a PIA release for Redhat / centos ?

Thanks

Regards

Ric

**Comment by dante1119** [comment]
Hi everybody,  
I have done a porting to centos 7 ... 
The only difficulty has been to 'translate' the libpq dependecny in postgresql redhat language that is postgresqlXX-devel + postgresqlXX-libs and finally bundling alla after manual fix of pg by 
gem install pg -v '0.21.0' --  --with-pg-config=/usr/pgsql-9.6/bin/pg_config 
cheers

**Comment by nwouda** [comment]
@xco51 I don't see how PIA would not be compatible with CentOS/RHEL in it's current state. Are you having any difficulties getting it up and running on CentOS/RHEL?
