### ISSUE TITLE
Issue in preview/print

### ISSUE THREAD

**Issue by SoftwareMagicIT** [LINCnil/pia#218]
In some cases preview and print not print complete document. This issue using backend with remote server.

**Comment by PapsOu** [comment]
I also notice that PIA (Example PIa) is printed with many useless white pages (see attached PDF)
[pia.pdf](https://github.com/LINCnil/pia/files/2034683/pia.pdf)

**Comment by PapsOu** [comment]
After a few tests, it appears that the print is OK on Chromium, but you need to wait a little bit in order to have the PIA completely loaded and printed.

**Comment by daniel84** [comment]
Good morning,
the pdf/print produced by printing the validated PIA presents some errors on the 3 charts representations for action plan (missing blu and green squares), risk overview (all the lines are in the upper left corner of the chart) and risk cartography (missing dots on the chart).
If I directly export the images everything is OK.
How can I solve the issues with the images in the printable version?

**Comment by brunto** [comment]
Hello,
Thank you for the feedback, we'll take a look soon to fix this.

**Comment by Wildvirus** [comment]
is there a solution?

**Comment by kevin-atnos** [comment]
Hello,

The Print functionnality has always been a little bit unstable, as it is handled by the browser and there are things that can hardly be managed (page breaks, etc).

The best way to get a better render of your PIA is to download the different files from your PIA in the "Print and download" block:
* .doc file (texts) ;
* .png files (visual elements, such as risk overview, risk mapping and action plan) ;
![image](https://user-images.githubusercontent.com/24872475/100897743-4e7b4a00-34c0-11eb-9554-efb4e80a0c18.png)

Then, customize the doc as you want. Add some personal styles: colors, fonts, page breaks, include the downloaded visuals...

From there, you can print it (directly from the doc you worked on, or from a .pdf you exported from the doc).
You will have a much better render than with the native Print function.

I hope this could help.

Kevin
