### ISSUE TITLE
[FEATURE REQUEST] AUTHENTIFICATION

### ISSUE THREAD

**Issue by MadDoxXimba** [LINCnil/pia#243]
Bonjour,

Est-il prévu une implémentation d'un système d'authentification (ex: basicAuth, ldap, ...)
[back et front]
Cordialement,
Jonathan

**Comment by peterhuerlimann** [comment]
Hi Jonathan,

This was negated in #134 .

Kind regards,
Peter

**Comment by MadDoxXimba** [comment]
Hi peterhuelimann,

Thanks for the answer!
I hope that this feature gets implemented ;)

Regards
Jonathan

**Comment by kevin-atnos** [comment]
Hello,

The next version (3.1) will have an authentication module with users, roles, profiles and rights management.
This new version should come this autumn 2021.

Thank you,

---

Bonjour,

Pour information, la prochaine version (3.1) contiendra un module de gestion des utilisateurs et de rôles/profils/droits.
Elle devrait arriver pendant l'automne.

Cordialement,

**Comment by PierreJonlet** [comment]
Bonjour,

où en sommes-nous dans cette possibilité ?

Respectueusement,
