### ISSUE TITLE
[FEATURE REQUEST] Adding measure to knowledge base.

### ISSUE THREAD

**Issue by MicroDrie** [LINCnil/pia#247]
Hallo,

Can it be made possible to add your own defined measures to the knowledge bank?

Kind regards,
Ruud van Driel

**Comment by kevin-atnos** [comment]
Hello,

In the latest versions, you can manage your own knowledge bases and specifically, create custom measures:

![image](https://user-images.githubusercontent.com/24872475/130761059-223dfe51-077d-4af4-b481-06fe0022f088.png)

Then you can use them in your PIAs, choosing your custom knowledge base on the right block:

![image](https://user-images.githubusercontent.com/24872475/130761261-2ae1d60a-5774-4b13-9c6d-259a2f7c8922.png)

Sincerely,
