### ISSUE TITLE
PIA v1.6.3 frontend/backend

### ISSUE THREAD

**Issue by KT223** [LINCnil/pia#261]
Hi, We have installed PIA v1.6.3 - having issues on 'Fundamental Principles' sections following review. Some of the selection buttons (Improvable/Acceptable etc.) and comments entered, are no longer selected or seen after a screen refresh. Despite this, the status is 'Subsection reviewed, awaiting final validation'. Also the 'Risk Mapping' is not being populated with any data. Other parts of the application seem to be working as expected. Can you help? 

Thanks,
Keith

**Comment by brunto** [comment]
Hello,
Could you record your screen to see the problem? We'll try to reproduce.
Thanks

**Comment by KT223** [comment]
Hi Bruno,

Just to let you know – we have downgraded back to v1.6.0 and are still seeing the same issues.

Data seems to be getting saved, but it’s the presentation layer having problems..

Any update from your review?

Best regards.
Keith





[cid:image008.png@01D43877.18AB7320]
Keith Thomson
Data Privacy Architect
EAR IT
Toyota Financial Services (UK) PLC
Great Burgh, Burgh Heath, Epsom, Surrey, KT18 5UZ
T: +44 (0)1737 365556   M: +44 (0)7713 981247
Email: keith.thomson@toyota-fs.com


[cid:image009.png@01D43877.18AB7320]<https://www.toyota.co.uk/my-finance.json>

© Toyota Financial Services - Protected

From: Keith Thomson
Sent: 13 August 2018 17:22
To: 'LINCnil/pia' <reply@reply.github.com>; LINCnil/pia <pia@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [LINCnil/pia] PIA v1.6.3 frontend/backend (#261)

Hi Bruno,
Many thanks.

Example –


1.
[cid:image010.jpg@01D43877.18AB7320]


2.       Complete section and then click ‘Validate Review’.
[cid:image011.jpg@01D43877.18AB7320]


Go back to this section and I see the following:

3.
[cid:image012.jpg@01D43877.18AB7320]

End of this section states:

[cid:image013.jpg@01D43877.18AB7320]

Also,
RISKS section is populated with data, but Risk Mapping (heat map) – no data.

[cid:image014.jpg@01D43877.18AB7320]


Best regards,
Keith




[cid:image015.png@01D43877.18AB7320]
Keith Thomson
Data Privacy Architect
EAR IT
Toyota Financial Services (UK) PLC
Great Burgh, Burgh Heath, Epsom, Surrey, KT18 5UZ
T: +44 (0)1737 365556   M: +44 (0)7713 981247
Email: keith.thomson@toyota-fs.com<mailto:keith.thomson@toyota-fs.com>


[cid:image009.png@01D43877.18AB7320]<https://www.toyota.co.uk/my-finance.json>

© Toyota Financial Services - Protected
