### ISSUE TITLE
Adding Risks

### ISSUE THREAD

**Issue by helrau** [LINCnil/pia#278]
Hi all,

it would be great to extend the risk areas. Right now basically I can only fill out 3 areas: privacy, integrity and data loss. I would like to add:

- non-concatenation, meaning the risk that different processing procedures and the data is concatenated

- minimisation,

 meaning the law to limit the storage of data of only needed data for the defined purpose

- intervention capability, meaning the capability of a private person to claim the personal rights: information, correcting, limiting, deleting etc. personal records

- Transperency,

**Comment by LaboCNIL** [comment]
Dear @helrau ,

The elements you raise are actually already covered in the Fundamental Principles section so it is doesn't look relevant to add them in the risk section.
