### ISSUE TITLE
Probleme avec URL serveur distant 

### ISSUE THREAD

**Issue by hhenoch** [LINCnil/pia#281]
Bonjour,
J'ai configuré le pia-back sur **http://ip:3000** et **ça fonctionne avec le client lourd PIA**.
Fonctionnent aussi : telnet ip 3000 et http://ip:3000 -> page blanche mais pas d'erreur.

J'ai ensuite installé le serveur pia front-end et l'accès http://ip:80 fonctionne correctement.
Mais lorsque sur le site web je paramètre dans outil l'accès au serveur distant (http://ip:3000 ) j'ai l'erreur :  connexion impossible

J'ai cherché dans tous les logs je ne vois pas d'où vient le problème. J'ai changé de browser : firefox, chrome, ie même problème.

Comment diagnostiquer le problème à partir du front-end web ?

**Comment by hhenoch** [comment]
Je rajoute ce qui suit sous **firefox** : 

1) j'affiche --> **outil développement --> stockage local.**
2) J'essaie de mettre à jour l'url du serveur distant : ca ne fonctionne pas comme dit précédemment
3) Je mets à jour l'url sans le port 3000 : ca fonctionne et apparaît dans "stockage local" la variable server_url
4) je modifie manuellement cette variable en mettant le port 3000 et là tout fonctionne

Donc j'en déduis qu'il y a bogue dans le bouton mettre à jour !!!!

**Comment by kevin-atnos** [comment]
Bonjour,

Nous allons étudier ce problème et le corriger s'il est présent pour la prochaine version qui sort très prochainement.

Merci

**Comment by hhenoch** [comment]
Merci bon courage

**Comment by brunto** [comment]
J'ai essayé pas mal de choses mais je n'arrive pas à reproduire l'erreur.
Est-ce qu'il serai possible de faire un partage d'écran ?

**Comment by zobi** [comment]
J'ai exactement le même soucis.
le pia-back fonctionne avec le client lourd
le pia front fonctionne en stand alone mais si j'indique l'url du pia back dans la config du front j'ai un message d'erreur "connexion impossible"
Merci d'avance

**Comment by brunto** [comment]
Il serai possible de faire un partage d'écran ou que vous nous fassiez une vidéo ?

**Comment by Charles68** [comment]
I'm facing the same issue. Setting the url manually in sqllite databes works.

**Comment by gbonnefille** [comment]
The same here. It seems that pia-back repond with **404** on `http://pia-back:3000/` while `http://pia-back:3000/pias` returns **200**. I suspect that:
- pia-back should returns something on root
- or pia-front should request something on the back, not the root directly (for example `/pias`)

**Comment by gbonnefille** [comment]
Seems related to https://github.com/LINCnil/pia-back/issues/26

Setting RAILS_SERVE_STATIC_FILES=true in the environment of the pia-back fixed my issue.

**Comment by brunto** [comment]
Nous avons identifié le problème et sommes entrain de le résoudre.

**Comment by liberodark** [comment]
perso je n'arrive pas à utiliser vos source.... et j'ai aussi le meme problème.

**Comment by liberodark** [comment]
For me is error 500 for /pias you have any idea ?

**Comment by chachabi** [comment]
J'ai le même soucis 
connexion a pia-back via le client lourd mais pas avec le front-end.
Y a t'il un moyen de fixer l'url autre que via le navigateur ??

**Comment by liberodark** [comment]
> For me is error 500 for /pias in POST request you have any idea ?

Fixed :+1:

**Comment by jhuet** [comment]
J'ai également le problème et je rejoins @chachabi , je pense qu'il pourrait être intéressant de pouvoir renseigner cette information autrement que via l'interface, pourquoi pas via une configuration ?

**Comment by gbonnefille** [comment]
Perso j'ai adapté le Dockerfile pour ajouter : 
```
ENV BACK_URL ""
RUN test -n "$BACK_URL" && sed -i ";</body>;<script type='text/javascript'>localStorage.setItem('server_url','${BACK_URL}');</script></body>;" /var/www/pia/dist/index.html
```

C'est pas top, mais ça fait le job.

**Comment by liberodark** [comment]
Solution for fix that try : https://github.com/LINCnil/pia/issues/251#issuecomment-470964122

**Comment by brunto** [comment]
Bonjour, nous avons corrigé cela dans la branche "Community" ce sera disponible dans la prochaine version  du logiciel.
