### ISSUE TITLE
[FEATURE REQUEST] Authentification et gestion de droits

### ISSUE THREAD

**Issue by blackspiderweb** [LINCnil/pia#298]
Bonjour,

Tout d'abord merci pour la mise à disposition de votre outil.

Nous aimerions le déployer sur notre intranet pour nos chefs de projets mais nous avons besoin d'implémenter un système d'authentification (on utilisera certainement un mod_authnz_ldap)
ainsi qu'un contrôle d'accès/gestion de droits pour la raison suivante :

=> Un document généré via l'outil PIA devra être accessible uniquement par son créateur et un groupe de validateurs.

Envisagez-vous d'implémenter ces mécanismes dans un futur proche ?

Si ce n'est pas le cas ... Pourriez-vous s'il vous plait m'aiguiller afin que je l'implémente moi même ?
J'ai jamais codé avec Ruby on Rail ou avec un framework style AngularJS donc si vous pouviez m'indiquer les bonnes pistes à suivre afin que je ne m'égare pas et que je ne perde pas trop de temps, ce serait fortement apprécié.

Merci d'avance.

**Comment by liberodark** [comment]
PS petite réponse j'ai fait un projet qui devrait vous aider à ce sujet mais intégrer le support ldap à pia serait pas mal.
https://github.com/YunoHost-Apps/pia_ynh

**Comment by nanii-60** [comment]
@liberodark pourriez vous détailler un peu plus sur le sujet ?

**Comment by liberodark** [comment]
Une fois fini oui pour l'instant je me heurte à un problème de connexion entre front et back malgré que les deux sont bien lancé correctement.
Mais dans l'ensemble cela ajoute une gestion utilisateurs et une auth déjà fonctionnel.

**Comment by kevin-atnos** [comment]
Bonjour,

Pour information, la prochaine version (3.1) contiendra un module de gestion des utilisateurs et de rôles/profils/droits.
Elle devrait arriver pendant l'automne.

Cordialement,

---

Hello,

The next version (3.1) will have an authentication module with users, roles, profiles and rights management.
This new version should come this autumn 2021.

Thank you,
