### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ifenice81** [LINCnil/pia#313]
I installed the Backend and the Frontend on a Debian 9.6 machine
I compiled the Frontend and moved the SRC directory to / var / www / html / and posted it in SSL.
The Frontend can be reached at https: //name-host.domain/
Launch the backend with the command RAILS_ENV = production bin / rails s -b 10.240.7.36 -p 3000 and first I try to connect with the installable client and everything is fine, instead putting http://10.240.7.36:3000 in the https: / /name-host.domain/ I receive an impossible connection.
I do not understand why with the installable client it works but from the Web it does not?

**Comment by brunto** [comment]
Hello,
This problem come from the CORS https://fr.wikipedia.org/wiki/Cross-origin_resource_sharing
You can check this PR https://github.com/LINCnil/pia/pull/178 we will review it soon.

**Comment by francescob** [comment]
Hello
I'm having the same problem, pia frontend app is on pia.mydomain.it
pia backend is on piabackend.mydomain.it
but it doesn't work because of cors errors, specifically:

> TypeError: Access-Control-Allow-Origin cannot contain more than one origin

any news about the pull request? or any other workaround I can use to make this configuration work?

Access from standalone app works correctly

**Comment by francescob** [comment]
good news: I've got it working by disabling the gem rack-cors on the backend application and adding this configuration on the virtual host of the backend app:

`Header set Access-Control-Allow-Origin "pia.mydomain.it"`

**Comment by ifenice81** [comment]
Hi Francesco
You Tell me nicely in which file you inserted the modification and how
Tnx

**Comment by francescob** [comment]
i have commented the whole content of the file cors.rb inside config/initializers/ of the backend application
then in the apache virtual host of the backend application I have added this line

`Header set Access-Control-Allow-Origin "addressofyourpiafrontendapp"`

**Comment by brunto** [comment]
We have just integrate the CORS inside the pia-back and pia.
See #322 and https://github.com/LINCnil/pia-back/pull/49
We'll release a new version soon.
