### ISSUE TITLE
Impossible de faire communiquer le back et le front

### ISSUE THREAD

**Issue by gentox123** [LINCnil/pia#327]
Bonjour,

Je n'arrive pas a faire communiquer le front avec le back.
J'ai suivi plus ou moins le run book et les instructions du github pour faire l'installation ..
Voici comment le back est lancé
[useradmin@fr-srv-templatehvmol7 pia-back]$ RAILS_SERVE_STATIC_FILES=true RAILS_ENV=production bin/rails s -b 192.168.0.56
=> Booting Puma
=> Rails 5.0.6 application starting in production on http://192.168.0.56:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.10.0 (ruby 2.3.8-p459), codename: Russell's Teapot
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://192.168.0.56:3000
Use Ctrl-C to stop

et le front:

[useradmin@fr-srv-templatehvmol7 pia]$ ng serve --host 0.0.0.0 --public-host 192.168.0.56 --target production
Your global Angular CLI version (7.3.4) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
** NG Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
Date: 2019-03-06T10:51:15.335Z
Hash: 79e80369dc6498afaaf0
Time: 65821ms
chunk {0} polyfills.ebd7aed4ca468af5834a.bundle.js (polyfills) 68.5 kB [initial] [rendered]
chunk {1} main.c47cdf44c73d1b52d741.bundle.js (main) 1.1 MB [initial] [rendered]
chunk {2} styles.1e96dfffff737e6b90b0.bundle.css (styles) 106 kB [initial] [rendered]
chunk {3} vendor.7dd98e4a787ee00a8a52.bundle.js (vendor) 1.21 MB [initial] [rendered]
chunk {4} inline.812ba51cb65d5b4729c0.bundle.js (inline) 798 bytes [entry] [rendered]
chunk {scripts} scripts.c5ee27172c0c12542b48.bundle.js (scripts) 533 kB [initial] [rendered]

webpack: Compiled successfully.

Lorsque je rentre l'adresse ip du serveur back dans les paramètres de l'interface web du front j'ai connexion impossible ( dans outils->Paramètre et mettre a jour l'url )?
Avez vous une solution ? une idée ?

Merci

**Comment by liberodark** [comment]
Un soucis inverse j'ai mis mon serveur communication réussi !
Normalement...

Mais pourtant impossible de créer un pia !

Auriez vous une idée ?

<a href="https://i.imgur.com/eDg6sn2.png">
  <img src="https://imgur.com/eDg6sn2l.png" />
</a>

**Comment by gentox123** [comment]
Perso j'ai du utiliser la version 1.6.4 du client web avec la 2.0.0 je n'ai pas réussi.

**Comment by liberodark** [comment]
Moi je cherche encore...
Comment les faire communiqué mais surtout comment le finir au propre.
Car je suis sur un projet assez important

**Comment by liberodark** [comment]
Voici ce que j'ai trouvé : 

<a href="https://i.imgur.com/Y9LVnSh.png">
  <img src="https://imgur.com/Y9LVnShl.png" />
</a>

Un problème CORS

**Comment by liberodark** [comment]
Résolu de mon coté : https://github.com/YunoHost-Apps/pia_ynh

**Comment by liberodark** [comment]
Corrigé aussi :D

**Comment by chachabi** [comment]
Même souci, comment le résoudre ??

**Comment by liberodark** [comment]
> Même souci, comment le résoudre ??

https://github.com/LINCnil/pia/issues/251#issuecomment-470964122

**Comment by brunto** [comment]
Nous avons implémenté tout cela sur la branche [PIA community branch (https://github.com/LINCnil/pia/tree/community) à utiliser avec la branche master de pia-back.
Une nouvelle version sortira bientôt avec ces corrections.
