### ISSUE TITLE
Question PIA ?

### ISSUE THREAD

**Issue by liberodark** [LINCnil/pia#330]
Bonjour,

J'ai installé pia front / back end dans la dernière version de git.
Tout fonctionne sauf que j'ai remarqué un truc quand on créer un pia il est lié à un cookie j'ai l’impression ce qui fait que si je change de navigateur ou de pc cela n'affiche pas les pia créer.
Je suis donc obligé de rester sur le même pc même navigateur.
Cela est il normale ?

Voici un exemple : 

<a href="https://i.imgur.com/xg3IlAR.png">
  <img src="https://imgur.com/xg3IlARl.png" />
</a>

A gauche Firefox et à droite Chrome, sur le même serveur pia.

Cordialement

**Comment by liberodark** [comment]
Vous pouvez faire le test sur : https://yunobox.ynh.ovh/pia/

**Comment by liberodark** [comment]
https://github.com/LINCnil/pia/issues/329#issuecomment-470980600

**Comment by liberodark** [comment]
Corrigé :D

**Comment by JohnMcReady** [comment]
Hello @liberodark 
Je me permet juste d'ajouter la correction
L'URL de back est stocké en local dans le navigateur donc il faut à chaque fois bien le renseigner si on utilise un autre navigateur !
Par contre moi maintenant j'ai un problème, quand je suis sur le front l'affichage après création du PIA est nickel mais si je suis sur le bo et bien pas l'affichage correct ...
![image](https://user-images.githubusercontent.com/53615870/63870227-d61f0280-c9b9-11e9-8650-a4493f53dcdc.png)
Si tu as une idée je suis preneur !! :-)
A+
