### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mdeweerd** [LINCnil/pia#346]
Installation sur debian 9

Après:

```
git clone https://github.com/LINCnil/pia.git
cd pia
npm install npm@latest -g
npm install -g @angular/cli
```

Tentative du build en mode production:
```
root@pia:~/pia# ng build --prod --build-optimizer --sourcemaps
The build command requires to be run in an Angular project, but a project definition could not be found.

```

Tentative avec yarn
```
root@pia:~/pia# yarn prod
ERROR: [Errno 2] No such file or directory: 'prod'
```

**Comment by brunto** [comment]
Bonjour,
Nous venons de mettre à jour la branche "master" avec Angular7 et diverses améliorations.
Cette version est encore en test mais vous pouvez l'utiliser.

**Comment by kevin-atnos** [comment]
@mdeweerd :

Bonjour,

Avez-vous pu tester avec la dernière version de l'outil PIA ?

Merci

**Comment by mdeweerd** [comment]
@kevin-atnos 
Je n'ai pas repris l'installation du projet qui n'est pour le moment plus à l'ordre du jour.
J'ai pour habitude de faire part des contretemps afin de contribuer à l'amélioriation des outils.
Cdmt
Mario
