### ISSUE TITLE
Add the ability to download the report in odt format

### ISSUE THREAD

**Issue by DimitrisTzellis** [LINCnil/pia#356]
Along with being able to export the report as a .zip or a .docx file, exporting the report as an OpenDocument Text (.odt) file.

Interoperability with open source software. No ties to proprietary office suites.
A clear and concise description of the issue that would be addressed.

LibreOffice, OpenOffice 
A list of examples of similar features encountered in other softwares and tools

**Comment by kevin-atnos** [comment]
Hello,

This was changed in the latest version. Now you can download an .odt file.
Also, we added date in the filename.

You can download the latest version there:
https://github.com/LINCnil/pia/releases/latest

Sincerely,

Kevin
