### ISSUE TITLE
[BUG] Installation fronted sur Ubuntu 18.4

### ISSUE THREAD

**Issue by lrasoanaivo** [LINCnil/pia#360]
**Description du bug / Describe the bug**
Une description concise et claire du bug rencontré.

Bonjour , 
Avec la version suivante 
Angular CLI: 7.3.9
Node: 8.10.0
OS: linux x64
Angular: 7.2.15

J'ai des erreurs sur la partie Fronted

oot@ubuntu18-uefi:~/rgpd/pia/pia# ng build --prod

Date: 2019-06-17T20:02:45.065Z
Hash: 769d9e50111a3ae16037
Time: 63983ms
chunk {0} runtime.26209474bfa8dc87a77c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} es2015-polyfills.bda95d5896422d031328.js (es2015-polyfills) 56.6 kB [initial] [rendered]
chunk {2} main.fa4681da67b0e16d34dc.js (main) 128 bytes [initial] [rendered]
chunk {3} polyfills.41559ea504b9f00b6dea.js (polyfills) 130 bytes [initial] [rendered]
chunk {4} styles.174229f6d7edccc2d838.css (styles) 94 kB [initial] [rendered]
chunk {scripts} scripts.d32783bacb7befdc70d7.js (scripts) 512 kB [entry] [rendered]

ERROR in src/app/summary/summary.component.ts(216,11): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/root/                                                                           rgpd/pia/pia/node_modules/html2canvas/dist/types/index")' has no compatible call signatures.
src/app/summary/summary.component.ts(273,11): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/root/rgpd/pia/                                                                           pia/node_modules/html2canvas/dist/types/index")' has no compatible call signatures.

Merci pour votre réponse
Lanto R.

**Comment by brunto** [comment]
Bonjour,
Pouvez-vous essayer en supprimant le dossier node_modules et en utilisant la branche "community" ?

**Comment by mazenovi** [comment]
Bonjour,
J'ai le même problème y compris avec la branch "community".
Existe t il un contournement?
Merci
