### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by RomainSanchez** [LINCnil/pia#361]
From instaling PIA back and front today i can see that the doc and runbook are outdated.

The runbook advises to use ruby 2.3.1 when the gemfile requires 2.5.5, for rails 2.0.6 instead of 2.0.7.

In the runbook again there is no mention of npm install for the frontend wich is of course mandatory to have the project working.

the runbook also recommends to use ng serve --prod for production purposes wich is a mistake. after ng build --prod a proper web server needs to be setup to point to the index like any other webpage.

From angular cli output of ng serve -- prod : `****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************`

Also it would be nice to document the fact that if the backend is not setup properly and configured in the frontend settings the data will be stored in the browser's storage.

I would suggest completely removing this feature as it is confusing.
you can think that everything is working fine and lose all your data because you reinstalled your browser or whatever. 

cheers

**Comment by FlorentChabaud** [comment]
Indeed I support the last recommendation to suppress the browser storage feature. In worldwide environments where you interact remotely with people, the problem appeared after several weeks when analysis and validation of DPIAs became to be asked. Or at least, put a BIG WARNING when URL is not properly set and give advice on how to backup and reimport PIAs.

Sincerely
