### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by sant0s** [LINCnil/pia#367]
**Description**
The ability to show/hide the left (index) and right (knowledge base) panels while editing.

**Issue or requirement solved by the feature**
It would provide a wider (editing) area, allowing the user to visualise more text. This is particularly relevant when the font size is increased (via ctrl shift plus) and even less text is visualised.

**Comment by kevin-atnos** [comment]
Hello,

Thank you for this suggestion, this seems to be a great idea.
We need to discuss this internally with the CNIL.

Kevin
