### ISSUE TITLE
Pia frontend fails with npm

### ISSUE THREAD

**Issue by kindkains** [LINCnil/pia#371]
Hi, I have installed the pia-backend and now I am trying to install also the frontend. I am using the runbook.

After

npm install npm@latest -g (which worked fine)

I have tried

npm install -g @angular-cli 

But then I get this error message:

`npm install npm@latest -g
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.10.0
added 14 packages from 10 contributors, removed 3 packages and updated 15 packages in 11.924s
[root@sdsgpia pia]# npm install -g @angular/cli
/usr/bin/ng -> /usr/lib/node_modules/@angular/cli/bin/ng

> @angular/cli@8.1.0 postinstall /usr/lib/node_modules/@angular/cli
> node ./bin/postinstall/script.js

/usr/lib/node_modules/@angular/cli/bin/postinstall/analytics-prompt.js:8
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/bin/postinstall/script.js:5:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @angular/cli@8.1.0 postinstall: `node ./bin/postinstall/script.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular/cli@8.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-04T10_16_03_196Z-debug.log`

How can I fix this?

I am running it on CentOS 7.6

`uname -a
Linux sdsgpia 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
`

**Comment by brunto** [comment]
Hi,
I think you must use the version 7 of Angular.
You can also simply use the standalone application.

**Comment by kindkains** [comment]
Thank you for your answer.
Meanwhile I could install/reinstall some of the packages/modules and got this part running. But I am still stuck in the next step. :-(

So I have just deleted my pia folder and tried to start the frontend installation from the beginning.

`
git clone https://github.com/LINCnil/pia.git

Cloning into 'pia'...
remote: Enumerating objects: 226, done.
remote: Counting objects: 100% (226/226), done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 13422 (delta 138), reused 148 (delta 97), pack-reused 13196
Receiving objects: 100% (13422/13422), 10.22 MiB | 7.43 MiB/s, done.
Resolving deltas: 100% (10988/10988), done.


cd pia
npm install npm@latest -g

/root/.nvm/versions/node/v12.6.0/bin/npm -> /root/.nvm/versions/node/v12.6.0/lib/node_modules/npm/bin/npm-cli.js
/root/.nvm/versions/node/v12.6.0/bin/npx -> /root/.nvm/versions/node/v12.6.0/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.10.0
updated 1 package in 6.844s

npm install -g @angular/cli

/root/.nvm/versions/node/v12.6.0/bin/ng -> /root/.nvm/versions/node/v12.6.0/lib/node_modules/@angular/cli/bin/ng

> @angular/cli@8.1.0 postinstall /root/.nvm/versions/node/v12.6.0/lib/node_modules/@angular/cli
> node ./bin/postinstall/script.js

? Would you like to share anonymous usage data with the Angular Team at Google under
Google’s Privacy Policy at https://policies.google.com/privacy? For more details and
how to change this setting, see http://angular.io/analytics. No
+ @angular/cli@8.1.0
updated 1 package in 57.539s


cp src/environments/environment.prod.ts.example src/environments/environment.prod.ts
vim src/environments/environment.prod.ts
`
content of environment.prod.ts

`export const environment = {
  name: 'production',
  production: true,
  version: '2.0.0'
};`

`ng build --prod --build-optimizer --source-map

You seem to not be depending on "@angular/core" and/or "rxjs". This is an error.`

This is the point I am stuck at the moment. Here are my system informations:

`node -v
v12.6.0`

`nvm ls
         v4.9.1
        v6.17.1
        v8.16.0
       v10.16.0
->      v12.6.0
         system
default -> node (-> v12.6.0)
node -> stable (-> v12.6.0) (default)
stable -> 12.6 (-> v12.6.0) (default)
iojs -> N/A (default)
lts/* -> lts/dubnium (-> v10.16.0)
lts/argon -> v4.9.1
lts/boron -> v6.17.1
lts/carbon -> v8.16.0
lts/dubnium -> v10.16.0`

`nvm --version
0.33.11`

`ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]`

`rails -v
Rails 5.2.3`

`psql -V
psql (PostgreSQL) 9.2.24`

`uname -a
Linux sdsgpia 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

I really need help to get this run and I have no experience with Angular, npm, nvm etc. just tried to follow the instructions in the run book, which did not work at all.

**Comment by brunto** [comment]
Could you try this:

```
npm uninstall -g angular-cli @angular/cli
npm cache clean --force
npm install -g @angular/cli@7.3.9
```

**Comment by kindkains** [comment]
Here we go:

`
npm uninstall -g angular-cli @angular/cli
removed 237 packages in 3.351s

npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.

npm install -g @angular/cli@7.3.9
/root/.nvm/versions/node/v12.6.0/bin/ng -> /root/.nvm/versions/node/v12.6.0/lib/node_modules/@angular/cli/bin/ng
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @angular/cli@7.3.9
added 289 packages from 179 contributors in 25.934s
`

This helped, thank you very much. But unfortunatly here is the next error:

`
ng build --prod --build-optimizer --source-map

Date: 2019-07-05T11:03:31.746Z
Hash: c981a349dc6cdebb0db4
Time: 21399ms
chunk {0} runtime.26209474bfa8dc87a77c.js, runtime.26209474bfa8dc87a77c.js.map (runtime) 1.46 kB [entry] [rendered]
chunk {1} es2015-polyfills.749cd189862ffeeebd50.js, es2015-polyfills.749cd189862ffeeebd50.js.map (es2015-polyfills) 56.6 kB [initial] [rendered]
chunk {2} main.fa4681da67b0e16d34dc.js, main.fa4681da67b0e16d34dc.js.map (main) 182 bytes [initial] [rendered]
chunk {3} polyfills.41559ea504b9f00b6dea.js, polyfills.41559ea504b9f00b6dea.js.map (polyfills) 189 bytes [initial] [rendered]
chunk {4} styles.d6d84bacce112665c6b0.css, styles.d6d84bacce112665c6b0.css.map (styles) 99.4 kB [initial] [rendered]
chunk {scripts} scripts.adf1be3ffceb4d03acdf.js, scripts.adf1be3ffceb4d03acdf.js.map (scripts) 514 kB [entry] [rendered]

ERROR in src/app/summary/summary.component.ts(194,11): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/opt/pia/node_modules/html2canvas/dist/types/index")' has no compatible call signatures.
src/app/summary/summary.component.ts(248,11): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/opt/pia/node_modules/html2canvas/dist/types/index")' has no compatible call signatures.
`

**Comment by brunto** [comment]
Are you on a 32-bit computer?

**Comment by kindkains** [comment]
Nope, it's 64 bit

`uname -m
x86_64`

**Comment by kindkains** [comment]
Meanwhile this step is working, but the next step fails again:

> ng build --prod --build-optimizer --source-map
> Your global Angular CLI version (8.1.2) is greater than your local
> version (7.3.9). The local Angular CLI version is used.
> 
> To disable this warning use "ng config -g cli.warnings.versionMismatch false".
> 
> Date: 2019-07-26T10:43:42.238Z
> Hash: c981a349dc6cdebb0db4
> Time: 21380ms
> chunk {0} runtime.26209474bfa8dc87a77c.js, runtime.26209474bfa8dc87a77c.js.map (runtime) 1.46 kB [entry] [rendered]
> chunk {1} es2015-polyfills.749cd189862ffeeebd50.js, es2015-polyfills.749cd189862ffeeebd50.js.map (es2015-polyfills) 56.6 kB [initial] [rendered]
> chunk {2} main.fa4681da67b0e16d34dc.js, main.fa4681da67b0e16d34dc.js.map (main) 182 bytes [initial] [rendered]
> chunk {3} polyfills.41559ea504b9f00b6dea.js, polyfills.41559ea504b9f00b6dea.js.map (polyfills) 189 bytes [initial] [rendered]
> chunk {4} styles.d6d84bacce112665c6b0.css, styles.d6d84bacce112665c6b0.css.map (styles) 99.4 kB [initial] [rendered]
> chunk {scripts} scripts.adf1be3ffceb4d03acdf.js, scripts.adf1be3ffceb4d03acdf.js.map (scripts) 514 kB [entry] [rendered]
> 
> ERROR in src/app/summary/summary.component.ts(194,11): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/opt/pia/node_modules/html2canvas/dist/types/index")' has no compatible call signatures.
> src/app/summary/summary.component.ts(248,11): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/opt/pia/node_modules/html2canvas/dist/types/index")' has no compatible call signatures.

**Comment by brunto** [comment]
@kindkains sorry for the delay, could you checkout and pull the current code on the branch "community" or "master"? and build with the command `yarn prod`.

**Comment by brunto** [comment]
I think the problem comes from `--source-map` you can try this command instead `ng build --prod --build-optimizer`

**Comment by kevin-atnos** [comment]
@kindkains Any news with this problem?

**Comment by jolssoncsam** [comment]
same problem here. ..
Resolve? 


***@chco7026:~/pia$ sudo ng build --prod --build-optimizer

Date: 2020-02-24T14:50:46.508Z
Hash: fd8beeef7b7d88e86524
Time: 17752ms
chunk {0} runtime.26209474bfa8dc87a77c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} es2015-polyfills.0ceb0abb4eda76a24a3d.js (es2015-polyfills) 56.6 kB [initial] [rendered]
chunk {2} main.fa4681da67b0e16d34dc.js (main) 128 bytes [initial] [rendered]
chunk {3} polyfills.41559ea504b9f00b6dea.js (polyfills) 130 bytes [initial] [rendered]
chunk {4} styles.94e60ae4b55d697dd5e1.css (styles) 94.4 kB [initial] [rendered]
chunk {scripts} scripts.201dd0b0cf647d31090c.js (scripts) 519 kB [entry] [rendered]

ERROR in src/app/preview/preview.component.ts(327,11): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/home/***/pia/node_modules/html2canvas/dist/types/index")' has no compatible call signatures.
src/app/preview/preview.component.ts(382,11): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/home/***/pia/node_modules/html2canvas/dist/types/index")' has no compatible call signatures.

**Comment by brunto** [comment]
@kindkains did you find a solution about this problem? I can't reproduce this in my local environment.
