### ISSUE TITLE
no title editing[BUG]

### ISSUE THREAD

**Issue by simosch137** [LINCnil/pia#376]
Hello, I use v.2.1.0 and there is no way to edit the title and the processor's and controller's details once drafting the PIA has started. Also, when duplicating the PIA so to be processed for another case, there is no way to change the title. Please advise

**Comment by brunto** [comment]
Hello, @simosch137 could you provide us more information about your OS and browser version?

**Comment by simosch137** [comment]
hello.. thanks for your interest. I use Windows 10 and Chrome 77.0.3865.90 64-bit

**Comment by brunto** [comment]
And when you click on the "title" you can't enter to edit? 
Like this:
<img width="425" alt="Screenshot 2019-10-09 13 29 43" src="https://user-images.githubusercontent.com/1003351/66477679-f0f49480-ea98-11e9-8360-ff804edc7281.png">

**Comment by kevin-atnos** [comment]
@simosch137 Any news about this problem?

**Comment by simosch137** [comment]
I have created one PIA as a prototype. When I want to create a new PIA for another client instead of writing everything from the beginning I only want to change some parts of the PIA. For that reason I duplicate the prototype. However when I choose to process the duplicated copy I miss the very first screen (the one you attached) and it starts directly from the second, ie the general framework of the PIA.

**Comment by kevin-atnos** [comment]
@simosch137 When you click on "Duplicate", you are directly redirected in this duplicated PIA instead of staying on the PIA card / list homepage ?

Can you provide us a video of the process please ?

Thank you

**Comment by kevin-atnos** [comment]
I close this issue for now, as we don't have enough data to figure out what happened.
If somebody encounters this too or if you can provide additionnal information about the problem, please, re-open this issue.
Thank you.
