### ISSUE TITLE
Running out of memory when building

### ISSUE THREAD

**Issue by edjw** [LINCnil/pia#377]
**Description du bug / Describe the bug**
Une description concise et claire du bug rencontré.

When you try to build the front end, the machine often runs out of memory. This seems to be a common issue with Angular builds.

I got it to build by using the following command:

```
node --max-old-space-size=1024 node_modules/@angular/cli/bin/ng build --prod
```

This limits the amount of memory it needs to build. You might want to consider adding this to the readme.

**Comment by brunto** [comment]
I have updated the README, it will be online in a few moment.
