### ISSUE TITLE
[BUG]Bug à la vérification de l'url du pia-back

### ISSUE THREAD

**Issue by Ivan-Rms** [LINCnil/pia#378]
Bonjour,
Voici un bug rencontré lors de l'ajout de l'url du back :

Lors de la première connexion à PIA, je souhaite ajouter l'url du serveur pia-back via "outils / paramètres"
- Lorsque l'on indique une url erronée, j'ai bien le message me disant "connexion impossible"
- En revanche lorsque j'ajoute la bonne url mais avec un espace à la fin ex : "http://localhost:3000 " PIA indique bien que la connexion avec le serveur a été établie, mais ne s'y connecte pas (les PIA existant dans la base de donnée ne s'affichent pas.

Il doit donc y avoir un bug lors de la vérification de l'url du serveur distant.

Pour reproduire le bug :
Se connecter sur le PIA, rajouter un espace sur l'url du serveur distant, cliquer sur "mettre à jour l'url" PIA indique que le serveur a bien été mis à jour, mais ne se connecte plus au pia-back (on ne voit plus les projets en cours).

**Comment by brunto** [comment]
Bonjour,
Effectivement on va faire en sorte de supprimer les espaces.
Merci pour le retour.

**Comment by kevin-atnos** [comment]
Bonjour,

Le problème a été corrigé et sera disponible dans la prochaine version qui sort très prochainement.

Cordialement,
