### ISSUE TITLE
PIA ne trouve plus les anciens projets

### ISSUE THREAD

**Issue by NoK80** [LINCnil/pia#379]
Bonjour,
Je rencontre un gros problème. Je ne trouve plus mes anciens projets que j'ai créé dans PIA. Il y a une semaine tous fonctionne correctement. La connexion avec le serveur se passe bien en utilisant l'url http://adresse_du_serveur:3000. Je n'ai rien modifié sur le serveur ni sur les paramètres du post client. 
Hier je me suis aperçu que tous mes projets ont disparu. Je n'arrive même pas à créer des nouveaux projet. Sur le serveur, j'ai trouvé que le PIA_Back n'est plus lancé. je la lancé en utilisant la commande 
RAILS_ENV=production bin/rails s
Après le lancement de ce commande j'arrive à créer des nouveaux projets mais mes anciens projet sont toujours pérdu. 
Merci de m'aider.

**Comment by brunto** [comment]
Bonjour,
Il faudrait aller vérifier directement en ligne de commande sur le serveur si les projets sont toujours dans la base de données. Je peux vous assister en partage d'écran si vous le souhaitez.
