### ISSUE TITLE
[FEATURE REQUEST] Open two or more PIA in parallel

### ISSUE THREAD

**Issue by frontibit** [LINCnil/pia#394]
**Description de la fonctionnalité que vous aimeriez avoir / Describe the feature you'd like**
I use the PIA tool and I like often switch from one PIA to another to look for information.
At the moment I need to go to dashboard, open the second one   take a look and go back to the first one.

Is it possible to have 2 open in parallel? (or at least run the software twice)

I'm using the tool on windows in the Portable app version.

**Comment by brunto** [comment]
The only way to do this is to compile pia-app without the option `requestSingleInstanceLock ` inside the main.js file.
