### ISSUE TITLE
Projets disparus

### ISSUE THREAD

**Issue by RomainFi** [LINCnil/pia#395]
Bonjour,

Apres avoir installe PIA sur l'un de nos serveur, nous l'avons laisse une semaine sans y toucher et en y revenant, pas moyen de revenir sur les projets crees il y a environ deux semaines.

En me connectant a postgresql, je peux voir une database avec le nom "pia_development" ainsi qu'une serie de table :

![Capture](https://user-images.githubusercontent.com/54840348/64945668-588c3b00-d871-11e9-807b-e16f9dd9b6b4.PNG)

Comment puis-je savoir si la database est bien chargee et si les modifications sont bien enregistrees dans celle-ci ?

Merci

Bien a vous.

Romain Fivet

**Comment by brunto** [comment]
Bonjour,
Si vous faire `SELECT * FROM pias;` vous avez la liste de vos PIA qui s'affiche ?

**Comment by RomainFi** [comment]
Bonjour Brunto,

Quand j'execute la commande, voici le resultat : 
![image](https://user-images.githubusercontent.com/54840348/64947188-c1c17d80-d874-11e9-9271-c0426737a351.png)

J'imagine que cela veut dire que je n'ai rien dans ma table :(

**Comment by RomainFi** [comment]
Bonjour,

Par rapport a ma question du 16/09, auriez-vous une idee quand a la configuration a checker sur le serveur ?

Le contenu fonctionne correctement, le site se comporte de maniere normale mais je vois la DB comme indique plus haut comme etant vide.

Merci

Bien a vous.

**Comment by brunto** [comment]
Je vous confirme que votre base de données est vide.
Il faudrait voir du côté de votre serveur l'origine de ce problème.
Je vous confirme que cela ne vient pas du logiciel PIA car ce dernier supprime un PIA uniquement si on clique sur le bouton "Supprimer" sur chaque fiche PIA.

**Comment by RomainFi** [comment]
Merci de votre reponse, auriez-vous un peu plus de precision quand a la localisation du probleme ?

**Comment by brunto** [comment]
Ça va être très compliqué sans étudier les logs du serveur.

**Comment by kevin-atnos** [comment]
@RomainFi :

Bonjour,

Avez-vous pu obtenir des informations concernant les logs de votre serveur ?

**Comment by TRSATOC** [comment]
Bonjour,

Je rencontre le même problème.
En fait je vois mes pias depuis le Front-end, mais rien n'est sauvegardé sur la BDD. Si je passe sur une navigation privée je ne vois plus mes projets

**Comment by brunto** [comment]
@TRSATOC Bonjour c'est normal car la navigation privée ne permet pas d'accéder aux données d'une navigation classique.

**Comment by TRSATOC** [comment]
Merci, j'ai cependant trouvé la solution a mon problème, le serveur n'était
pas correctement paramétré via le front-office.
Il serait cependant utile d'indiquer que les sauvegardes en BDD n'ont pas
eu lieu dans ce cas

Le mer. 4 déc. 2019 à 12:06, Bruno Perles <notifications@github.com> a
écrit :

**Comment by RomainFi** [comment]
Hello @TRSATOC 

Pourriez-vous me dire ce que vous avez modifie exactement ?

J'aimerai etre sur de ne pas avoir la meme erreur.

merci

Bav

**Comment by kevin-atnos** [comment]
Bonjour,

De manière générale, n'hésitez pas à suivre les instructions de "pia-back" : 
https://github.com/LINCnil/pia-back#run-the-application
Afin d'installer et de brancher correctement le Front et le Back de l'outil PIA.

Cordialement,
