### ISSUE TITLE
[BUG] Pièces jointes en .bin

### ISSUE THREAD

**Issue by Darkpiou** [LINCnil/pia#397]
Bonjour,

Les pièces jointes ajoutées au PIA se changent en .bin
Les pièces jointes sont bien dans le répertoire ../pia-back/data/attachment/attached_file mais en .bin au lieu d'être en .pdf. Quand je les ajoute elles sont pourtant bien pdf.
Je ne comprends pourquoi il y a le changement d'extension du fichier.

Y a-t-il des fichiers de conf à modifier ?

Merci pour votre aide.

Serveur :
OS : Centos 7.6
BDD : PostgresSql 9.6
Web : Back PIA + PIA sous httpd

**Comment by brunto** [comment]
C'est corrigé dans https://github.com/LINCnil/pia-back/commit/8f720cd1937562a0fc3cc0c7e8935b35c1160f7d
Ce sera dispo dans la prochaine release.
