### ISSUE TITLE
[BUG]the software does not save

### ISSUE THREAD

**Issue by tresrob** [LINCnil/pia#399]
hi I installed the pia and pia-back platform using the @ppmotskula script. Unfortunately I have seen that the forms can be compiled only with the use of Chrome does not work firefox and neither explorer.
Entering a new pia after each step the data is not stored.
If I go out and come back, everything is lost.
Could you please help me? Where do the procedure logs reside?
Thanks

**Comment by kevin-atnos** [comment]
@brunto assisted @tresrob and they solved the problem together.
Closed issue.
