### ISSUE TITLE
Missing Button "Display action plan" [BUG]

### ISSUE THREAD

**Issue by Wildvirus** [LINCnil/pia#447]
In release 2.2.0 I'm missing the button "Display action plan" to export the information to pdf. 

Using 2.2.0 on Windows 10 64bit 
![PIA_Win10](https://user-images.githubusercontent.com/9499201/71879206-d086b580-312d-11ea-90be-917bab15a1d3.png)

Using 2.2.0 on Windows 7 64bit
![PIA_Win7](https://user-images.githubusercontent.com/9499201/71879208-d086b580-312d-11ea-82f0-0411ccbb5f66.png)

**Comment by Wildvirus** [comment]
any information about the bug ?

**Comment by brunto** [comment]
@Wildvirus Is this issue still exist in 2.3.0?

**Comment by Wildvirus** [comment]
@brunto Sorry for the late answer. Yes, in 2.3 the buttons moved to the left but the Button "Disply action plan" is still missing

**Comment by kevin-atnos** [comment]
Hello,

The process changed but I can't remember when. Maybe in 2.2. That's probably why you no longer have the old text and button for "Display action plan" as it was changed.

- Now you can edit your PIA while it's in progress : **pencil button**
- Then you can consult it (preview mode / display action plan) when it's validated (simple or signed validation) : **eye button**
![image](https://user-images.githubusercontent.com/24872475/96456542-e843ac00-121e-11eb-9b26-22d321622427.png)
From there, you can print/export to .pdf

This change was discussed internally with the CNIL.
