### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jolssoncsam** [LINCnil/pia#455]
Why are we unable to start this one in Ubunti 18 following the guide? 
It's like a never ending story of dependency issues.

7026:~/pia$ sudo ng build --prod --build-optimizer

Date: 2020-02-24T14:50:46.508Z
Hash: fd8beeef7b7d88e86524
Time: 17752ms
chunk {0} runtime.26209474bfa8dc87a77c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} es2015-polyfills.0ceb0abb4eda76a24a3d.js (es2015-polyfills) 56.6 kB [initial] [rendered]
chunk {2} main.fa4681da67b0e16d34dc.js (main) 128 bytes [initial] [rendered]
chunk {3} polyfills.41559ea504b9f00b6dea.js (polyfills) 130 bytes [initial] [rendered]
chunk {4} styles.94e60ae4b55d697dd5e1.css (styles) 94.4 kB [initial] [rendered]
chunk {scripts} scripts.201dd0b0cf647d31090c.js (scripts) 519 kB [entry] [rendered]

ERROR in src/app/preview/preview.component.ts(327,11): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/home/****/pia/node_modules/html2canvas/dist/types/index")' has no compatible call signatures.
src/app/preview/preview.component.ts(382,11): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/home/****/pia/node_modules/html2canvas/dist/types/index")' has no compatible call signatures.

**Comment by brunto** [comment]
I close this issue to centralize the conversation inside https://github.com/LINCnil/pia/issues/371
