### ISSUE TITLE
[BUG] new version PIA v2.3

### ISSUE THREAD

**Issue by Fabienne-l** [LINCnil/pia#497]
Bonjour,
Je vous fais part des principaux bugs que j'ai rencontrés dans la nouvelle version PIA v2.3:
• Sur la page d'accueil des PIA, la vision d’une ligne n’est pas globale, il faut faire défiler le curseur
• L’impression de l’AIPD est aussi mauvaise voire moins bien qu’en v2.2.1
• Attention les PJ ne se voient pas et donc ne sont pas accessibles en v2.3 ; il faut les réimporter
A quand une version PIA qui donne un rendu propre de l'analyse?
Merci et bonne journée!
FL

Hello,
I share with you the main bugs that I encountered in the new PIA v2.3 version::
• On the PIA home page, the vision of a line is not global, you have to scroll the cursor
• The impression of the PIA is as bad or worse than in v2.2.1
• Be careful the enclosed document cannot see each other and therefore cannot be accessed in v2.3; they must be reimported
When will a PIA version give a clean work?
Thank you and good day!
FL

@Fabienne-l

**Comment by brunto** [comment]
Bonjour,
Pouvez-vous nous fournir par messagerie à l'adresse suivante bruno@atnos.com :
- des captures d'écrans
- le PDF à imprimer afin de voir le rendu 
Concernant les pièces jointes, parlez-vous d'un export/import ? ou d'une perte des pièces jointes lors du passage de la 2.2 en 2.3 ?
