### ISSUE TITLE
Installation guide for Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by paedi18** [LINCnil/pia#502]
Hello

Does anyone have a installation guide/runbook for the full PIA Back & Front Installation on a Ubuntu 20.04 LTS Server?

Thanks.

**Comment by brunto** [comment]
Hello @paedi18,
I'm currently writing a guide for ubuntu, I will send it to you as soon as it is available.

**Comment by contributorx** [comment]
Bonjour à tous,
Tout d'abord merci pour vos posts qui m'ont permit de m'en sortir assez facilement avec une installation faîte sur Ubuntu Server 20.04 et oui LTS....
J'ai pris le Book d'antoinep30 pour m'en inspirer
Cependant j'ai rencontré quelques problèmes lors de son exécution que j'ai réussi à à résoudre...
Je partage tout naturellement le fichier modifié avec les commandes qui m'ont permit de ne pas avoir d'erreur après plusieurs installations...
Je me suis concentré sur l'installation en production....

RUNBOOK_UBUNTU_20.04 V2.txt

**Comment by paedi18** [comment]
Hello contributorx

Thank you very much for the Runbook. 
Where can I download it?

**Comment by contributorx** [comment]
Hi
You can download it on this page🤙🏻

Envoyé de mon iPhone

**Comment by contributorx** [comment]
[Uploading RUNBOOK_UBUNTU_20.04 V2.txt…]()

**Comment by paedi18** [comment]
I still cannot download it :/

**Comment by contributorx** [comment]
https://github.com/LINCnil/pia/issues/505
You can download it on this link on my other post🤙🏻

**Comment by brunto** [comment]
You can find an updated runbook on the wiki: https://github.com/LINCnil/pia-back/wiki
