### ISSUE TITLE
Complete overhaul in Angular 10

### ISSUE THREAD

**Issue by brunto** [LINCnil/pia#503]
We are currently rewriting the project on Angular 10. We'll have better performance and code organization.

**Comment by kevin-atnos** [comment]
Hello,

The complete overhaul with Angular **11** is almost ready, we are doing the final tests.
This new version will probably come as a PIA 3.0 release, with all the new features supposed to be released in the 2.4 version (custom knowledge bases, ...).
Stay tuned!

Kevin

**Comment by DschingisKahn** [comment]
Any news on the new version?

**Comment by brunto** [comment]
The new version is online: https://github.com/LINCnil/pia/releases/tag/v3.0.0
