### ISSUE TITLE
Installation on Ubuntu Server 20.04 LTS

### ISSUE THREAD

**Issue by contributorx** [LINCnil/pia#505]
Bonjour,
Après avoir durement travaillé sur divers problèmes rencontrés lors de l'installation de Pia front et back je vous fait part du runbook crée par Antoine PUECHLONG que j'ai modifié afin d'avoir une installation sans erreurs.
J'étais comme beaucoup un peu perdu au début maintenant j'y vois beaucoup plus clair.
Si ça peut aider une autre personne j'en serais ravis....
A vos claviers 

[RUNBOOK_UBUNTU_20.04 V2.txt](https://github.com/LINCnil/pia/files/5435503/RUNBOOK_UBUNTU_20.04.V2.txt)

**Comment by brunto** [comment]
Bonjour @contributorx 
Merci pour cette contribution on va s'en servir et compléter celui que nous sommes en train de faire. Nous allons mettre cela dans le Wiki du projet Github afin de centraliser l'information.

**Comment by Nicolas-ld** [comment]
Bonjour,

Je tente une installation avec votre guide mais j'ai une erreur à la commande rvm install ruby-2.6.5
"Warning: Failed to create the file ruby-2.6.5.tar.bz2.part: Permission denied"

Apparemment un problème de droits mais je ne trouve pas ou?

Merci.

**Comment by Nicolas-ld** [comment]
J'ai trouvé pour ceux qui auront le même problème
rvm group add rvm "$USER"
log out et log in
Vérifier avec la commande id que l'utilisateur est bien dans le groupe rvm
lancer 
rvm fix-permissions

et ca roule ..

**Comment by brunto** [comment]
Bonjour, nous avons centralisé toutes les informations des divers contributeurs dans le wiki : https://github.com/LINCnil/pia-back/wiki

**Comment by contributorx** [comment]
Bonsoir,
Beau travail merci pour les infos!
À bientôt

Envoyé de mon iPhone
