### ISSUE TITLE
Wrong version number displayed[BUG]

### ISSUE THREAD

**Issue by contributorx** [LINCnil/pia#506]
Problem with version show on pia-front
When i upgraded my pia-web version 2.0 to version 2.3.0 i show on my site pia the old version.
I show that in the file home/user/pia-2.3.0/src/environments/environment.prod.ts.example that the old version is always in this file.
Don't forget to modify this file and enter the correct updated version for resolve this bug.

Thanks

**Comment by brunto** [comment]
Thank you @contributorx we'll change the information.
