### ISSUE TITLE
Passage de htpp à https

### ISSUE THREAD

**Issue by contributorx** [LINCnil/pia#510]
Bonjour,
Je voulais savoir comment faire pour passer mon pia front et back en https?
Pour la partie front j'ai bien configuré le mode https via apache et la création d'un virtual host avec les certificats qui vont bien pas de soucis....
Cependant une fois le front passé en https il ne parvient plus à communiquer avec la partie back...
Pouvez-vous m'aider pour passer pia-back en mode https ou me donner la marche à suivre?

Merci d'avance

**Comment by onosh** [comment]
Bonjour,

Pour commencer, je vous conseil de monter la solution avec le dépôt [pia-docker](https://github.com/kosmas58/pia-docker) (adaptez le fichier docker-compose selon vos envies..)

Ensuite, il suffit de configurer un reverse proxy nginx, de cette manière par exemple :
https://hackmd.io/@onosh/r1LEMPIiv

onosh

**Comment by pinpin-xici** [comment]
Bonjour, j'ai le même souci que contributorx, comment faire ? En effet une fois le front mis en https ça ne fonctionne plus car le back lui n'est pas en https. Savez vous comment régler le problème ? Je ne désire pas pour  le moment utiliser docker.  Merci

**Comment by brunto** [comment]
Bonjour,
Il vous faut aussi mettre en place un certificat SSL sur le serveur qui héberge le backend (pia-back).
Vous pouvez utiliser certbot https://certbot.eff.org

**Comment by cece46** [comment]
voici un script que je lance en service : 

`

#! /bin/bash
source "/etc/profile.d/rvm.sh"

cd /opt/pia-back-master






echo "-----update sys----"
#gem update --system
echo "-----update----"

#bin/bundle update --bundler
echo "--------indtal----"
#gem install nokogiri -v '1.10.7'
#sudo bundle install
echo "---------rvm----"

echo "---------lunch----"

#RAILS_SERVE_STATIC_FILES=true RAILS_ENV=production bin/rails s -b xx.xx.xx.xx -p 3000
RAILS_SERVE_STATIC_FILES=true RAILS_ENV=production bin/rails s -b 'ssl://xx.xx.xx.xx:3000?key=/etc/nginx/ssl/key.key&cert=/etc/nginx/ssl/key.cer'

cd /opt/pia

npm run-script start


`
