### ISSUE TITLE
[FEATURE REQUEST] Riskmap does not show extra information from the whole PIA

### ISSUE THREAD

**Issue by karansorey** [LINCnil/pia#513]
I would like to request a feature that could be helpful.  there is only an overview of the risk map and not of the rest of the information entered from the whole PIA, for example a small piece about the project itself. It could be helpfull to have more extra information about the PIA in the Risk map

**Comment by kevin-atnos** [comment]
Hello @karansorey,

You can go in one of your PIAs and use the download options in the right block of the screen.
There, you can get a .doc file containing all PIA information, visual elements (risk map, action plan, risk overview), the action plan detail (.csv) and some other data.

You can then use these files as you want if you want to make a full docx with pictures, or use them in some PowerPoint, and so on.

Sincerely,
