### ISSUE TITLE
[BUG] Unable to import PIA from diffrent user

### ISSUE THREAD

**Issue by lukaszgrochola** [LINCnil/pia#514]
Unable to import PIA exported file, from diffrent user

1. Create PIA file on user A
2. Export PIA on user A and send it to diffrent user
3. Import on any other user than A fails to import without error. Through json file or zip

Expected behavior
Importing from diffrent user to share his PIA should work

**Spécifications / Specification (please complete the following information):**

 - OS: Microsoft WIndows 10 Enterprise 18363
 - Browser [e.g. chrome, safari]: Portable version, directly installed on computer
 - Tool Version [e.g. 2.0]: 2.2.0 / 1.6.3

User can export his PIA and only import only his own PIA.

**Comment by lukaszgrochola** [comment]
PIA sometimes exports single json, json file in archive, dat or even without extension. 
I've manage testing and i can import 3 testing files. 
.json
no extension file
json extracted from zip file

Most of the zipped files, even after extracting cant be imported.

**Comment by brunto** [comment]
Hello @lukaszgrochola 
If you try to import a JSON file from version 2.x to version 1.6.X, it will not work. You need to upgrade your app to the latest version.

**Comment by lukaszgrochola** [comment]
So all we need is stick to one version 1.6.3 and one day upgrade to incoming version 3.0

**Comment by kevin-atnos** [comment]
Hello @lukaszgrochola,

Did you (and your partners) update your PIA tool to the latest version?
(3.0.1 : https://github.com/LINCnil/pia/releases/tag/v3.0.1) ?

Does the problem still occur?

Thank you
