### ISSUE TITLE
[FEATURE REQUEST]Permanent Connection Config to backend ?

### ISSUE THREAD

**Issue by aelri-c** [LINCnil/pia#520]
Everytime a browser session is launched the connection the back ends needs to configured under settings.
Is there not a way to make this permanently configurable?

**Comment by brunto** [comment]
You can't, the setting is only stored on your browser session for security reasons.

**Comment by florian-bellencontre** [comment]
@brunto In this case we would need an alert explaining that no backend is configured and that our documents will not be saved.

**Comment by aelri-c** [comment]
I know you can't hence I labelled this a feature request. The problem is if the setting is in the browser session then it needs to be reconfigured every single time a user accesses the app.

As for it being a security reason. I really don't see that it provides any security (other than potentially through obscurity). Security in a web application should never rely on the user interface configurations. 

A better security feature would be integration to an LDAP server, for authentication.
