### ISSUE TITLE
[BUG] Appel API Inexistante /pias/{pia_id}/revisions:

### ISSUE THREAD

**Issue by TheMalloum** [LINCnil/pia#526]
**Description du bug / Describe the bug**
J'intègre le PIA a un backend custom à partir du fichier swagger.yaml
Je m'appercoit que l'interface PIA fait un appel d'une API inexistante : 

/pias/{pia_id}/revisions:

**Etapes pour le reproduire / To Reproduce**
Décrivez les étapes pour reproduire le comportement anormal:
à la création d'un PIA

**Comment by brunto** [comment]
Bonjour,
Le fichier swagger n'est pas à jour, on est entrain de basculer toute la doc de l'API sur Postman afin que ce soit plus facile à utiliser. Ce sera prêt ce mois-ci.
Vous pouvez voir toutes les routes utilisées dans le fichier routes.rb du projet pia-back : https://github.com/LINCnil/pia-back/blob/master/config/routes.rb Si vous installez le projet pia-back vous pouvez lancer la commande `bin/rake routes` permettant de lister toutes les routes.

**Comment by kevin-atnos** [comment]
Bonjour,

Nous avons terminé de basculer la documentation de l'API sur Postman, vous pouvez la retrouver ci-dessous :
https://api.atnos.io/
Nous continuons de l'améliorer au fur et à mesure.

Cordialement,
