### ISSUE TITLE
[BUG] l'export d'une base de connaissance ne contient pas les éléments renseignés

### ISSUE THREAD

**Issue by chartz** [LINCnil/pia#556]
Les éléments présents dans la base de connaissance ne sont pas présent dans le fichier d'export de la base de connaissance.

**Comment by brunto** [comment]
@chartz Merci du retour, nous allons regarder cela.

**Comment by kevin-atnos** [comment]
Bonjour @chartz ,

Désolé pour la réponse tardive.
Effectivement, merci pour le retour, nous travaillons sur un correctif qui sera très bientôt disponible.

Merci à vous.

Kevin

**Comment by kevin-atnos** [comment]
Bonjour @chartz ,

Ce problème a été résolu dans la dernière version que nous venons de publier :

Vous pouvez la récupérer en suivant ce lien :
https://github.com/LINCnil/pia/releases/latest

N'hésitez pas à nous dire à ré-ouvrir l'issue si le problème persiste.

Cordialement,

Kevin
