### ISSUE TITLE
An insecure SockJS connection may not be initiated from a page loaded over HTTPS [front 3.0.0]

### ISSUE THREAD

**Issue by cece46** [LINCnil/pia#557]
PIA Front 3.0.0 / Backend 2.3.0

Depuis la version 3.0.0 du Front j'ai cette erreur au lancement du site Web que je n'avais pas en 2.3.0 du front. La page ne s'ouvre pas, j'ai seulement le cercle qui tourne de chargement et ceci dans la console du navigateur : 

![image](https://user-images.githubusercontent.com/32593390/124237208-8fe7dc80-db17-11eb-8eb6-b7cfd113e771.png)

```
Uncaught Error: SecurityError: An insecure SockJS connection may not be initiated from a page loaded over HTTPS
    at new SockJS (sockjs.js:689)
    at new SockJSClient (SockJSClient.js:43)
    at initSocket (socket.js:20)
    at Object.<anonymous> (client:176)
    at Object.kNy/ (vendor.js:121203)
    at __webpack_require__ (bootstrap:79)
    at Object.0 (measure.model.ts:9)
    at __webpack_require__ (bootstrap:79)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
```

Voici mon architecture et configuration: 

[CLIENT] -------> [    SERVEUR PIA (NGINX+FRONT+BACKEND)       ]
User        ------->[    NGINX : 443 >> PIA FRONT 127.0.0.1:8088 ]
User        ------->[    Backend : 3000 ]

Dans le package.json du front : 
```
"start" : "ng serve --host 127.0.0.1 --port 8088 --public-host --servePath=/ --disable-host-check
```

Le lancement du backend se fait comme suit:  
```
RAILS_SERVE_STATIC_FILES=true RAILS_ENV=production bin/rails s -b 'ssl://xx.xx.xx.xx:3000?key=key.bin&cert=certificate.cer'
```

Dans la config nginx (que je n'ai pas touché puisque fonctionnel en 2.3.0 du front PIA), je fais juste un proxy_pass. Bien évidemment j'ai déclaré dans NGINX les cer/key pour etre parfaitement en https avec un nom de domaine : 
```
  proxy_pass http://127.0.0.1:8088;
```

Malgré tout cela, j'ai toujours cette erreur citée plus haut. J'ai testé en http sur le port 80 avec l'IP du serveur : aucun problème, le site fonctionne sans erreur, me propose le choix du backend et ça marche (je peux voir les PIA etc...) Mais dans un besoin de sécurité, je souhaite rester en https. 

J'ai également testé depuis l'application "lourde" électron, et ça marche puisqu'il ne doit pas utiliser un certificat SSL pour afficher la page. 

Est-ce un problème de la version 3.0.0 ou est-ce ailleurs ? Pouvez vous m'éclairer svp  ?

Merci à tous de vos propositions. 

Bien  à vous.

**Comment by brunto** [comment]
Bonjour,
Dans un premier temps je vous conseille d'utiliser la version 3.0.0 du backend https://github.com/LINCnil/pia-back/releases/tag/v3.0.0 
Ensuite, je vous conseillerai d'utiliser aussi NGINX pour le backend avec un certificat SSL sur le port 443.
Nous avons rédigé une documentation à ce sujet :
https://github.com/LINCnil/pia-back/wiki/Configure-Nginx-for-PIA-BACK
et
https://github.com/LINCnil/pia-back/wiki/Enable-SSL-for-HTTPS
Je pense que ça devrait résoudre votre erreur.

**Comment by syl-p** [comment]
Bonjour @cece46 ! 
En lisant votre issue, je vois que vous avez modifié le script "**start**" du package.json pour lancer le projet en mode développement sur votre serveur. 

Mais, je ne pense pas que cela soit une bonne pratique d'héberger le projet de cette manière. En effet le compilateur ouvre des sockets pour observer les changements sur les fichiers sources en mode "**yarn start**" ou "**npm run start**". 

Cela pourrait expliquer l'erreur que vous avez lorsque vous souhaitez passer par une adresse en https.

La bonne pratique (selon moi) serait d’héberger sur votre serveur le projet pia (front) compilés grâce à la commande "**yarn prod**" ou "**npm run prod**" ( suite à cette commande les sources seront dans le dossier ./dist ). 

J'espère vous avoir aidé.
Bonne journée.

**Comment by cece46** [comment]
Merci @brunto  de votre retour. 
Je me suis peut être mal exprimé, mais j'ai un certificat SSL sur le NGINX sur le FRONT, et j'utilise aussi les mêmes certificats sur le backend.  Les flux sont bien chiffrés.
J'ai profité de mettre à jour le backend : J'ai toujours le même soucis de SockJS ;

@syl-p  merci de votre retour. 
J'ai donc compilé et appliqué la config de nginx proposée. J'ai toujours le même soucis de SockJS ;

**Comment by cece46** [comment]
J'ai cependant une nouvelle erreur : 

```
vendor.js:123049 Uncaught Error: SecurityError: An insecure SockJS connection may not be initiated from a page loaded over HTTPS
    at new SockJS (vendor.js:123049)
    at new SockJSClient (vendor.js:19413)
    at initSocket (vendor.js:35729)
    at Object.<anonymous> (vendor.js:121202)
    at Object.kNy/ (vendor.js:121203)
    at __webpack_require__ (runtime.js:80)
    at Object.0 (main.js:1215)
    at __webpack_require__ (runtime.js:80)
    at checkDeferredModules (runtime.js:46)
    at Array.webpackJsonpCallback [as push] (runtime.js:33)

```
