### ISSUE TITLE
Suppression mesure existante impossible 

### ISSUE THREAD

**Issue by pierrebazin** [LINCnil/pia#563]
Bonjour, 
Erreur JS lors d'une suppression d'une mesure existante. 

![image](https://user-images.githubusercontent.com/26218504/126155158-3d9087e0-52dd-4755-909d-8d9aa1a8e50f.png)

![image](https://user-images.githubusercontent.com/26218504/126155121-26e9c2b9-8f73-4da4-9102-6a193b37cd06.png)

Cordialement,

**Comment by kevin-atnos** [comment]
Bonjour,

Merci pour votre retour. Nous allons regarder ce soucis et préparer un fixe.

Cordialement,

Kevin

**Comment by syl-p** [comment]
Bonjour @pierrebazin,
Je suis en train de regarder votre soucis. Pouvez vous me dire quelle version du projet vous êtes en train d'utiliser ?

Merci.

**Comment by pierrebazin** [comment]
Bonjour, 
désolé pour le délais de retour. Je suis en version **1.6**

![image](https://user-images.githubusercontent.com/26218504/127011782-287155df-805d-41d7-a634-4ffd5cd72939.png)

**Comment by syl-p** [comment]
Bonjour @pierrebazin, nous avons dans les dernières versions corrigés un certain nombre d'erreurs similaires et celle là a déjà été traitée me semble t'il.

Si une fois à jours, vous rencontrez des problèmes similaires, n'hésitez pas à nous les signaler.
