### ISSUE TITLE
Print PIA - Unable to print visualisation of Action plan

### ISSUE THREAD

**Issue by saadlalam** [LINCnil/pia#564]
Hello,

We're encountering an issue where printing a PIA does not print the colored squares in the Action plan.
![actionPlanOverview](https://user-images.githubusercontent.com/26288471/127462258-25b48796-cacd-4785-b362-510e8a5c4ed9.png)

This seems to happen for all our PIAs, and here's an exported example :
[https://api.jsonbin.io/b/61026e712ccb97077c14473f](url)

also, there's an error in the console, whenever we access the validation part : 
<img width="358" alt="Screenshot 2021-07-29 at 10 42 21" src="https://user-images.githubusercontent.com/26288471/127463272-40e021aa-f03d-45fc-bdb9-e3dbb945526c.png">

Any ideas what might cause it ?

Thanks in advance !

**Comment by syl-p** [comment]
We will check that soon. Could you say what is the app version ? 

Thanks to you for reporting this issue.

**Comment by saadlalam** [comment]
We've noticed this on version 3.0.0 (last) where graphs don't always appear in the summary after completing 100% of the PIA, nor during printing, and sometimes only after browser clearing cache storage but we have another version 2.1.0 where the action plan does not appear during printing.

**Comment by saadlalam** [comment]
Hello,
little update, now I've just tried with the version 3.0.1 :
 -Same issue for action plan : colored squared don't appear when printing. (Could it be linked to the fonts used ?  as there are some 'decoding awesome-font' warnings on the console).
 -A new console error appearing `Cannot read property 'style' of null`
 -Unable to print Risk mapping levels background : 
 
 Thank you for this great project !
 The attachment explains some of the issues.
![image](https://user-images.githubusercontent.com/26288471/127859497-73e9b425-0d25-4b66-9ef3-c8dc8c23364b.png)

**Comment by syl-p** [comment]
Hello @saadlalam. We don't forget your issue. I'm working on this. 

This error appear for every pias in your app ? Or only one ? 
Can you screen the whole errors list that appear in your console ? Thanks.

**Comment by syl-p** [comment]
Hello @saadlalam, I found an answer to your problem.
[You need to check your print option](https://stackoverflow.com/questions/3893986/css-media-print-issues-with-background-color)

I check this by myself and Voilà !

![Capture d’écran du 2021-08-10 14-31-27](https://user-images.githubusercontent.com/50445384/128867236-087fd62b-c83a-425a-ba34-13513d555ea1.png)
