### ISSUE TITLE
export to .docx no longer has the heading information like the title of the PIA, the people involved, ...

### ISSUE THREAD

**Issue by lucpijpers** [LINCnil/pia#565]
Since version 3.0 when exporting the text to .docx, the document no longer has the heading infomation like :

PIA information.
PIA 
Pia Name
Autors 
XYZ
Reviewer
ABC
Validator's 
DEF
Date
16/07/2019

**Comment by kevin-atnos** [comment]
Hello @lucpijpers ,

Sorry for the late answer.
Thank you for the feedback, we are working on a fix which will be soon available.

Kevin

**Comment by kevin-atnos** [comment]
Hello,

This was fixed in the latest version. 
You can download it there:
https://github.com/LINCnil/pia/releases/latest

Feel free to re-open this issue if the problem still appears.

Sincerely,

Kevin
