### ISSUE TITLE
Replace inline style with a class

### ISSUE THREAD

**Issue by cilex-ft** [LINCnil/pia#577]
The text editor in sections Measures, Questions, Evaluations... has no style and appears in Times New Roman font.

This is set by line

    content_style: 'body {background-color:#eee!important;}',

in these files:

* content/questions/questions.component.ts
* content/evaluations/evaluations.component.ts
* content/measures/measures.component.ts
* structure/content/measures/measures.component.ts
* structure/content/questions/questions.component.ts

We're working to customize the appearance of PIA-front, and we'd prefer avoiding hacking the sources.

When initializing tinymce, can you please use ```content_css``` rather than ```content_style``` and link it to the main css? Or, if you can't link to the main.css, load some separate css in /assets/stylesheets/?

Thank you, and congrats for this nice program!

**Comment by kevin-atnos** [comment]
Hello,

We will have a look at this and will let you know if we can make an update with the team.

Thank you!

**Comment by kevin-atnos** [comment]
Hello @cilex-ft ,

# General
We have pushed an update for TinyMCE styles on the `master` branch.
Indeed, this wasn't the best to have it in raw, so we no longer use `content_style` and we put the style for the background color directly in `src/assets/stylesheets/_editor.scss`.
See: https://github.com/LINCnil/pia/pull/583/files

Is it better for you this way?

## Sidenote
You can also add some CSS in this file to update other stuff from tinyMCE.
Here is a simple way to do it and test it:
- Go in src/app/modules/pia/content/questions/questions.component.ts and comment line 470 `this.closeEditor();`
- Enter in some PIA and open TinyMCE for the first question from the first section, for example
- Open your browser and check the DOM / inspect the TinyMCE elements
- Add your styles with classes/IDs in this editor css file
- Test it
- Uncomment line 470 from  src/app/modules/pia/content/questions/questions.component.ts when everything is fine to you

Thank you for the feedback!
