### ISSUE TITLE
I18N - Changes to translations - @atnos/pia-i18n is archived. 

### ISSUE THREAD

**Issue by kenso23** [LINCnil/pia#614]
I want to use this nice tool! 

But there is an issue with the translation to Danish. My company is a scandinavian company and we might want to use this - cross nations. How can we change / Suggest changes to the translations. The @atnos/pia-i18n what seem to have the i18n json files has been archived. But the solution seems to dependt on it. 

Please advise.

**Comment by kenso23** [comment]
Found it i think. Reopening, if that is not the case!

**Comment by brunto** [comment]
Hello, yes all the translations are under the LINCnil repository: https://github.com/LINCnil/pia-i18n
