### ISSUE TITLE
Cannot import pia on the server that was exported from the standalone client

### ISSUE THREAD

**Issue by acrauser** [LINCnil/pia#621]
I exported a pia that was created and done on the standalone client.

When trying to import the pia in the frontend-backend combination on the server, the pia is imported but the complete content is empty. The only data available is the metadata (creator, Name, ...) of the pia.

The server log (production.log) show not errors, however see traces like that:
D, [2022-01-03T14:45:45.178263 #1] DEBUG -- : [c8bba9d4-1135-493a-b44d-a3c47ac787cd]    (22.9ms)  BEGIN
D, [2022-01-03T14:45:45.267539 #1] DEBUG -- : [c8bba9d4-1135-493a-b44d-a3c47ac787cd]   Pia Load (52.5ms)  SELECT "pias".* FROM "pias" WHERE "pias"."id" = $1 LIMIT $2  [["id", 0], ["LIMIT", 1]]
D, [2022-01-03T14:45:46.020586 #1] DEBUG -- : [c8bba9d4-1135-493a-b44d-a3c47ac787cd]    (17.8ms)  ROLLBACK
I, [2022-01-03T14:45:46.044960 #1]  INFO -- : [c8bba9d4-1135-493a-b44d-a3c47ac787cd] Completed 422 Unprocessable Entity in 1197ms (Views: 1.2ms | ActiveRecord: 175.2ms | Allocations: 16314)

**Comment by mariopaolucci** [comment]
Hello and thanks for all your work,

I also am in a similar situation - my Ubuntu 21.10 machine runs the local application fine, but cannot reload its own saves. It goes, ```The imported file doesn't correspond to a PIA report file```. 

I have checked `.config/pia/pia/logs` but it is empty. 

Please advise, especially if there's some workaround already?

**Comment by brunto** [comment]
Hello,
I think you should open the JSON file with a text editor and look for strange characters.
If you find smtg strange, try to remove the characters and save the file to another name to try to import it again.

**Comment by mariopaolucci** [comment]
Dears,

I was just trying to load the zipped file that you get by exporting.

Unzipping and then loading works. I would suggest changing the error message to "this isn't a json PIA report file" for first time users.

Best

**Comment by acrauser** [comment]
Sorry, but why was the issue closed? Is there a bug fix for my problem?
I find the comment "look for strange characters in the json" a little bit funny. It's an export that was done by your software so how should I rate what characters are strange?

**Comment by syl-p** [comment]
Sorry, I understood that your problem was due to the fact that you import the entire zip. Not the Json file as requested. That right ?

**Comment by syl-p** [comment]
Sorry, I understood the problem was relative to a full zip import instead only json file. Issue reopened.

**Comment by acrauser** [comment]
Hi,

No the problem is related to importing the json file. Basically, it is not importing the content of the export so that only the metadata (Name of pia, etc.) is available.
The can easily be tested by creating a test pia with some small content, exporting it and then reimporting it.

**Comment by kevin-atnos** [comment]
Hello @acrauser,

Can you tell us the PIA version you are working on? (exporting and importing on which PIA version?)

Thank you

**Comment by acrauser** [comment]
Hi,
 Sure it’s 3.0.2

Kind regards,
Andreas

**Comment by brunto** [comment]
Did you copy-paste from Microsoft Word?
If yes, try to delete the content pasted and then export/import the PIA again.

**Comment by SoufianeBenrazzouk** [comment]
Hello.
i had the same issue and finally found a way to resolve this.
But first i have to explain one thing: in my case, when i go to parameters -> URL server Config, and if i leave it blank, and import my pia.json, everything works, but it loads on the local machine only.
but when i put the server URL, any import doesn't work anymore.

So here is what I did :
1) I leave the URL server config blank and import the pia. ->if it's similar to me, the pia should be complete.
2) Archive the pia.
3) put the right url server configuration.
4) unarchive the pia, by going to My PIAs -> Archived PIAs
5) the pia should appear on the server, complete, and shared.

It's not a normal way to make it work, but it did the trick for me.

**Comment by Ricman0** [comment]
Hi, I have the same issue. The exported Pias from standalone client cannot be imported correctly on the server mode app despite it is a well-formatted Json and the import on client mode app works well. When I try to import the exported Pias, I get the errors reported in the image taken from the browser console and only metadata of the Pia are imported.
![Pia Errors Importing](https://user-images.githubusercontent.com/11945880/151708357-087ffd49-16bb-473c-9d53-ba28820f40b8.PNG)

**Comment by Ricman0** [comment]
Any news about the issue?

**Comment by syl-p** [comment]
@Ricman0, We have make some fixes and test about your problem and on the last version (master) everything is working fine. Have you try upgrade your app version ?

**Comment by kevin-atnos** [comment]
Hello,

Does anyone still have some issues about import / export with the latest PIA version?
If so, please can you provide which tests you made (from which version to which version, details on the imports / exports, ...).
Thank you;
