### ISSUE TITLE
Impossible to Import/Export

### ISSUE THREAD

**Issue by Gringostar8** [LINCnil/pia#643]
We are using PIA V3.0.3 and 3.0.2, we are working on various PIa but lately when we try to export and import the file, an error message is displayed when trying to import telling that the file is not a valid PIA file
sometimes the export is a ZIP file with the json file in it, sometimes (for the same project) the export is just a file, in both case impossible to import it.
I ve made some cross test and it s never working 
from the same pc exporting and trying to import the same fil=error message
from one PIA to another laptop=same eror message
creating a new pia/ export it and trying to import it on the same laptop=error message
Could you please help

**Comment by Gringostar8** [comment]
missing some info
We are using the Win 10 stand alone version
https://github.com/LINCnil/pia/releases/download/v3.0.3/pia-Setup-3.0.3.exe

**Comment by brunto** [comment]
Hello @Gringostar8 I think the file is corrupted. Did you copy/paste data from a Microsoft Word document?

**Comment by Gringostar8** [comment]
Hi @brunto, in this case all my files are corrupted because i ve tried on many export and different laptops, i have always the same issue. Even if i create a new PIA test and export it i have this issue so i don t think files is corrupted.

**Comment by brunto** [comment]
Ok so even with an empty PIA you have the issue!
Are you ok to do screen sharing, this way I could help you more quickly? If yes, you can contact me by email (see my profile page https://github.com/brunto)

**Comment by brunto** [comment]
This problem is solved, the problem was caused by Windows BitLocker which removed the ".zip" extension from the export archive.
