### ISSUE TITLE
Créer un utilisateur at accèder au pia front

### ISSUE THREAD

**Issue by ccousin-ddn** [LINCnil/pia#668]
Bonjour
Auriez vous une documentation pour expliquer comment prendre en main l'outil
J'ai installé le front et back sur un serveur que vous pouvez voir ici : http://pia.devdunet.fr/
mais le front demande une identification.
Serait-il possible de m'expliquer ce que je dois faire ?
D'avance merci
Cédric COUSIN

**Comment by brunto** [comment]
Bonjour,

Avez-vous bien configuré le mode Authentication via la procédure du README ?

https://github.com/LINCnil/pia-back#enable-the-authentication-mode <https://github.com/LINCnil/pia-back#enable-the-authentication-mode> 

Je peux vous proposer de faire un partage d’écran afin que je puisse vous aider.

Cordialement,
Bruno Perles

**Comment by ccousin-ddn** [comment]
Bonjour
Il me semble oui l'avoir fait comme décrit dans la documentation
Serait-il possible de ce fait de faire un partage d'écran ? Quand pourrions nous l'envisager ?
Cordialement

**Comment by brunto** [comment]
Bonjour,
Vous pouvez trouver mon email sur mon profil https://github.com/brunto j'ai des disponibilités semaine prochaine idéalement à 13h30 mardi ou mercredi prochain
Cordialement

**Comment by syl-p** [comment]
Problème résolu lors de l'entretien fait avec Mr @ccousin-ddn. Je ferme l'Issue
