### ISSUE TITLE
How to remove a comment?

### ISSUE THREAD

**Issue by dennisbaaten** [LINCnil/pia#678]
I'm the standalone EXE (Windows 10) of the PIA tool. I added a comment, but I want to remove it. How to do this?

**Comment by syl-p** [comment]
This feature is not enable actually but this could be added to the app in the future.

**Comment by dennisbaaten** [comment]
Is there a workaround? For example: can I manually edit a SQLlite database or something like that?

**Comment by syl-p** [comment]
Yes sure ! 
In standalone mode (without pia-back) you have to go into the indexDb section of your browser. 

Here example on chrome: 
![image](https://user-images.githubusercontent.com/50445384/197475656-43781b31-90a2-4547-8240-bceb63c799ab.png)
