### ISSUE TITLE
Help needed for frontend/backend authentication

### ISSUE THREAD

**Issue by pnprog** [LINCnil/pia#708]
Hello,

I installed pia and pia-back using the wiki

- pia on localhost:80
- pia-back on localhost:8080

They both run using apache2, I can open both of then in the web browser. So it seems to be working.

To connect the front to the back end, a client ID and SECRET are required, how to generate them?

![image](https://user-images.githubusercontent.com/25114663/221798222-ab301797-fdc4-4d0a-b4a7-8427d32444b7.png)

In the back end README (https://github.com/LINCnil/pia-back#run-the-application), the form does not include the client ID and SECRET. Is there a way to simply remove that authentication when running through apache2?

Thanks and best regards

**Comment by syl-p** [comment]
Hello ! You must follow this section to enable you authentification mode:

https://github.com/LINCnil/pia-back#enable-the-authentication-mode

**Comment by syl-p** [comment]
Hello ! You must follow this section to enable you authentification mode:

https://github.com/LINCnil/pia-back#enable-the-authentication-mode

Client ID is the "uid" attribute from the Doorkeeper::Application instance.
![image](https://user-images.githubusercontent.com/50445384/223066773-42d3ed62-82be-4cc0-b49c-2cf81f9713cc.png)

**Comment by syl-p** [comment]
If like me you have a [FILTERED] value, do this: 

```
Doorkeeper::Application.first.secret
```

**Comment by pnprog** [comment]
Thanks, I will try that!
