### ISSUE TITLE
Node 16 déprécié

### ISSUE THREAD

**Issue by Pigment-RomainLoisel** [LINCnil/pia#735]
**Description du bug / Describe the bug**

Le projet utilise Node 16 qui est déprécié depuis le 11 septembre 2023 (https://nodejs.org/en/blog/announcements/nodejs16-eol).
Pour des raisons de sécurité, est-il possible de mettre à jour le projet à une version de node supportée svp ?

**Comment by syl-p** [comment]
Bonjour, @Pigment-RomainLoisel
Nous venons de migrer l'application angular vers angular 15 (sur master). On utilise là encore la version 16.17.0 (voir .tools-version). Je vais essayer de voir si tout compile sur une version supérieure de nodejs. 

Je vous tiens informé.
Bonne journée.

**Comment by kevin-atnos** [comment]
Bonjour,

Nous venons de mettre à jour Node en 20.10.
Les changements sont disponibles sur la branche principale "master" et seront intégrés dans le prochain build / la prochaine version.

Bien cordialement,
