### ISSUE TITLE
Yarn Prod command fails on pia version 3.2.2.

### ISSUE THREAD

**Issue by ektorasdj** [LINCnil/pia#745]
Hello and thank you for this tool.
When trying to run yarn prod (after yarn install) inside the /var/www/pia I get this error: 

./src/environments/environment.ts:5:11-30 - Error: Should not import the named export 'version' (imported as 'packageJson') from default-exporting module (only default export is available soon)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Can you help me?

**Comment by syl-p** [comment]
We just merged a pull request from a contributor fixing this issue.
https://github.com/LINCnil/pia/pull/746/files

Thanks for reporting this problem. To get yarn prod succeded, just "git pull" on the master branch.

**Comment by syl-p** [comment]
We just merged a pull request from a contributor fixing this issue.
https://github.com/LINCnil/pia/pull/746/files

Thanks for reporting this problem. To get yarn prod succeded, just "git pull" on the master branch.
