### ISSUE TITLE
User Management Enhancement Request

### ISSUE THREAD

**Issue by ylachgar** [LINCnil/pia#75]
Hi All,

Is it possible to include somehow a user management to allow segregation of  PIA work from different workstreams ? 
Maybe a group Management and a User Management ?

Thanks in advance

**Comment by kevin-atnos** [comment]
Hello,

The next version (3.1) will have an authentication module with users, roles, profiles and rights management.
This new version should come this autumn 2021.

Thank you,

---

Bonjour,

Pour information, la prochaine version (3.1) contiendra un module de gestion des utilisateurs et de rôles/profils/droits.
Elle devrait arriver pendant l'automne.

Cordialement,
