### ISSUE TITLE
Installation front-end failing [version 3.0.3]

### ISSUE THREAD

**Issue by boterocamilo** [LINCnil/pia#768]
Hi,

I am trying to install the version 3.0.3 on a PC running Debian 12. Despite being able to install the back-end (even with many of the requirements outdated), when proceeding with the installation of the front-end, it results impossible, mainly because of the dependencies and libraries are outdated, and they are not compatible (and secure) with what I have installed on.

Is there any way to install the version 3.2.2 (back and front-end), and do you think this will solve the compatibility issue with the outdated requirements?

Thanks in advance for any help you can provide.

**Comment by brunto** [comment]
Hello,

The wiki on the pia-back is based on the 22.04 Ubuntu version: https://github.com/LINCnil/pia-back/wiki 
Maybe it will be easier on a Ubuntu server?

**Comment by kevin-atnos** [comment]
Hello,

Did you manage to install your Front/Back using the Wiki?

Feel free to re-open this issue if needed.

Regards,
