### ISSUE TITLE
Multiple Translations (GER, ITA, ...)

### ISSUE THREAD

**Issue by gruselglatz** [LINCnil/pia#9]
Like the nl.json maybe we can create a German version. I don't know the template syntax, so a empty German version would be helpful to fill it.

**Comment by CirKu17** [comment]
In this regard, I activated myself for the translation to Italian with @inelemento . 
I have set up a Weblate installation and I'm currently working on the translation. If the mantainer  (@LaboCNIL ) and someone else is interested I could arrange a hosted version of the instance.

**Comment by gruselglatz** [comment]
i would love to use this tool. I've never done a translation via Weblate but count me in on that.

**Comment by LaboCNIL** [comment]
Hi,
If you wish to translate the tool in any language, please refer to the following tutorial : https://github.com/LINCnil/pia/tree/master/src/assets/i18n
Some translations have already been submitted and we would welcome yours as well!

**Comment by GianlucaMarkos** [comment]
Hi LaboCNIL/All, I just shared the first version of it.json file with a pull request. I started to create the italian version with my team in @identitadigitaledefender group.

We are tech people and legal staff and we are "GDPR open source" oriented. I also send you here the file partially completed with txt extension for team review [itjson.txt](https://github.com/LINCnil/pia/files/1582952/itjson.txt). 

I think this translaltion, for be user friendly and alligned with italian legal/tech terms (in the specific context) should be done online with other italian delegate in the team. So, I took the task to start the work and I shared the file here for give freedom to other italian partecipant to update it directly in the common github workspace.

Thanks to colleagues (and all the others) which started this very nice project! Good work to all and merry christmas.

**Comment by CirKu17** [comment]
Hi @GianlucaMarkos , I was already working on the italian translation (forked with my agency @inelemento) as I wrote earlier but I didn't confronted our progresses yet. 
How can I participate with my translations?
Also, leave me a way to contact you or your group since I'd like to explore partnership possibilities. 
Cheers.

**Comment by GianlucaMarkos** [comment]
Sure you can partecipate... it's open project and my scope is to share the file with all of you. I already made a pull request for share my ready part.. I think you can update directly my it.json file here in GitHub, if @LaboCNIL will accept it. I'll contact you from your website contacts number if you would like or do the same with me. You find me on linkedin too. And partnerships are my job. Waiting for your news I wish you a merry christmas.
