### ISSUE TITLE
Savoir si le serveur de base de données est opérationnel

### ISSUE THREAD

**Issue by Logicsystem360** [LINCnil/pia#90]
Bonjour,

Il serait pas mal de rajouter un message pour confirmer (ou pas) le fonctionnement avec la base de données.
En effet lorsque que la base de données n'est pas fonctionnelle ni accessible, il n'y a pas de message d'erreur.

**Comment by brunto** [comment]
Bonjour,
Vous parlez en mode Client/Serveur ou en mode standalone ?

**Comment by brunto** [comment]
Avec la dernière version de PIA 2.0 il y a la vérification du serveur distant avec un message précisant si il est accessible ou non.
